# Payment Completion Flow (v1)
# Handles the post-payment experience - confirmation, notifications, and tracking

name: payment_completion_v1
version: '1.0'
description: Post-payment order confirmation and notification flow

# Triggered after successful payment callback
triggers:
  - type: event
    event: payment_success
  - type: webhook
    path: /payment/callback

variables:
  order_id: ''
  payment_id: ''
  payment_method: ''
  amount_paid: 0
  order_details: null
  vendor_name: ''
  estimated_time: 0

nodes:
  # Entry - Verify payment and get order details
  - id: verify_payment
    type: action
    action: php_api
    params:
      action: verify_payment
      payment_id: '{{payment_id}}'
      order_id: '{{order_id}}'
    outputs:
      payment_verified: verified
      order: order_details
      vendor: vendor_info
    next: check_payment_status

  - id: check_payment_status
    type: condition
    conditions:
      - condition: '{{payment_verified}} == true'
        next: payment_success
      - condition: '{{payment_verified}} == false'
        next: payment_failed
    default: payment_pending

  # Payment Success Flow
  - id: payment_success
    type: action
    action: set_session_context
    params:
      current_order_id: '{{order_id}}'
      order_status: 'confirmed'
    next: send_customer_confirmation

  # Send order confirmation to customer
  - id: send_customer_confirmation
    type: message
    message:
      en: |
        тЬЕ *Payment Successful!*
        
        *Order #{{order_details.order_id}}*
        
        ЁЯТ░ *Amount Paid:* тВ╣{{amount_paid}}
        ЁЯТ│ *Payment Method:* {{payment_method}}
        
        *Items:*
        {{#each order_details.items}}
        тАв {{this.quantity}}x {{this.name}} - тВ╣{{this.total}}
        {{/each}}
        
        *Total:* тВ╣{{order_details.total}}
        
        ---
        
        ЁЯУН *Delivery to:*
        {{order_details.delivery_address}}
        
        ЁЯПк *From:* {{vendor_info.store_name}}
        
        тП▒я╕П *Estimated Time:* {{estimated_time}} minutes
        
        ---
        
        Your order has been sent to the restaurant. We'll notify you when they confirm it!
        
        Reply *TRACK* to track your order anytime.
      hi: |
        тЬЕ *рднреБрдЧрддрд╛рди рд╕рдлрд▓!*
        
        *рдСрд░реНрдбрд░ #{{order_details.order_id}}*
        
        ЁЯТ░ *рднреБрдЧрддрд╛рди рд░рд╛рд╢рд┐:* тВ╣{{amount_paid}}
        ЁЯТ│ *рднреБрдЧрддрд╛рди рд╡рд┐рдзрд┐:* {{payment_method}}
        
        *рдЖрдЗрдЯрдо:*
        {{#each order_details.items}}
        тАв {{this.quantity}}x {{this.name}} - тВ╣{{this.total}}
        {{/each}}
        
        *рдХреБрд▓:* тВ╣{{order_details.total}}
        
        ---
        
        ЁЯУН *рдбрд┐рд▓реАрд╡рд░реА рдкрддрд╛:*
        {{order_details.delivery_address}}
        
        ЁЯПк *рд╕реЗ:* {{vendor_info.store_name}}
        
        тП▒я╕П *рдЕрдиреБрдорд╛рдирд┐рдд рд╕рдордп:* {{estimated_time}} рдорд┐рдирдЯ
        
        ---
        
        рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рд░реЗрд╕реНрддрд░рд╛рдВ рдХреЛ рднреЗрдЬ рджрд┐рдпрд╛ рдЧрдпрд╛ рд╣реИред рдЬрдм рд╡реЗ рдкреБрд╖реНрдЯрд┐ рдХрд░реЗрдВрдЧреЗ рддреЛ рд╣рдо рдЖрдкрдХреЛ рд╕реВрдЪрд┐рдд рдХрд░реЗрдВрдЧреЗ!
        
        рдХрднреА рднреА рдЕрдкрдирд╛ рдСрд░реНрдбрд░ рдЯреНрд░реИрдХ рдХрд░рдиреЗ рдХреЗ рд▓рд┐рдП *TRACK* рднреЗрдЬреЗрдВред
      mr: |
        тЬЕ *рдкреЗрдореЗрдВрдЯ рдпрд╢рд╕реНрд╡реА!*
        
        *рдСрд░реНрдбрд░ #{{order_details.order_id}}*
        
        ЁЯТ░ *рднрд░рд▓реЗрд▓реА рд░рдХреНрдХрдо:* тВ╣{{amount_paid}}
        ЁЯТ│ *рдкреЗрдореЗрдВрдЯ рдкрджреНрдзрдд:* {{payment_method}}
        
        *рдЖрдпрдЯрдо:*
        {{#each order_details.items}}
        тАв {{this.quantity}}x {{this.name}} - тВ╣{{this.total}}
        {{/each}}
        
        *рдПрдХреВрдг:* тВ╣{{order_details.total}}
        
        ---
        
        ЁЯУН *рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрддреНрддрд╛:*
        {{order_details.delivery_address}}
        
        ЁЯПк *рдкрд╛рд╕реВрди:* {{vendor_info.store_name}}
        
        тП▒я╕П *рдЕрдВрджрд╛рдЬрд┐рдд рд╡реЗрд│:* {{estimated_time}} рдорд┐рдирд┐рдЯреЗ
        
        ---
        
        рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рд░реЗрд╕реНрдЯреЙрд░рдВрдЯрд▓рд╛ рдкрд╛рдард╡рд▓рд╛ рдЖрд╣реЗ. рддреЗ рдкреБрд╖реНрдЯреА рдХреЗрд▓реНрдпрд╛рд╡рд░ рдЖрдореНрд╣реА рддреБрдореНрд╣рд╛рд▓рд╛ рдХрд│рд╡реВ!
        
        рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рдЯреНрд░реЕрдХ рдХрд░рдгреНрдпрд╛рд╕рд╛рдареА рдХрдзреАрд╣реА *TRACK* рдкрд╛рдард╡рд╛.
    next: trigger_vendor_notification

  # Trigger vendor notification (multi-channel)
  - id: trigger_vendor_notification
    type: action
    action: notify_vendor_new_order
    params:
      vendor_id: '{{vendor_info.id}}'
      vendor_phone: '{{vendor_info.phone}}'
      vendor_fcm_topic: '{{vendor_info.zone_wise_topic}}'
      order_id: '{{order_id}}'
      order_amount: '{{order_details.total}}'
      customer_name: '{{session.customer_name}}'
      items_count: '{{length(order_details.items)}}'
      items_summary: '{{order_details.items_summary}}'
      payment_method: '{{payment_method}}'
    outputs:
      notification_sent: notification_sent
    next: log_order_created

  # Log order creation for analytics
  - id: log_order_created
    type: action
    action: log_event
    params:
      event_type: order_created
      order_id: '{{order_id}}'
      amount: '{{amount_paid}}'
      vendor_id: '{{vendor_info.id}}'
      payment_method: '{{payment_method}}'
      channel: 'whatsapp'
    next: wait_for_customer_response

  # Wait for customer response
  - id: wait_for_customer_response
    type: input
    input_type: text
    timeout: 300  # 5 minutes timeout
    next: process_response

  - id: process_response
    type: condition
    conditions:
      - condition: 'match({{input}}, "^(track|рдЯреНрд░реИрдХ|рдЯреНрд░реЕрдХ)$", "i")'
        next: transfer_to_tracking
    default: acknowledge_response

  - id: acknowledge_response
    type: message
    message:
      en: "Got it! ЁЯСН We'll keep you updated on your order status."
      hi: "рд╕рдордЭ рдЧрдпрд╛! ЁЯСН рд╣рдо рдЖрдкрдХреЛ рдЖрдкрдХреЗ рдСрд░реНрдбрд░ рдХреА рд╕реНрдерд┐рддрд┐ рд╕реЗ рдЕрдкрдбреЗрдЯ рд░рдЦреЗрдВрдЧреЗред"
      mr: "рд╕рдордЬрд▓реЗ! ЁЯСН рдЖрдореНрд╣реА рддреБрдореНрд╣рд╛рд▓рд╛ рддреБрдордЪреНрдпрд╛ рдСрд░реНрдбрд░рдЪреНрдпрд╛ рд╕реНрдерд┐рддреАрдмрджреНрджрд▓ рдЕрдкрдбреЗрдЯ рдареЗрд╡реВ."
    next: end_flow

  - id: transfer_to_tracking
    type: flow_transfer
    target_flow: customer_order_status_v1

  # Payment Failed Flow
  - id: payment_failed
    type: message
    message:
      en: |
        тЭМ *Payment Failed*
        
        We couldn't process your payment for Order #{{order_id}}.
        
        *Reason:* {{payment_error}}
        
        Don't worry, no amount has been deducted from your account.
        
        Would you like to:
        1. ЁЯФД Try again
        2. ЁЯТ│ Use a different payment method
        3. тЭМ Cancel order
      hi: |
        тЭМ *рднреБрдЧрддрд╛рди рд╡рд┐рдлрд▓*
        
        рд╣рдо рдСрд░реНрдбрд░ #{{order_id}} рдХреЗ рд▓рд┐рдП рдЖрдкрдХрд╛ рднреБрдЧрддрд╛рди рдкреНрд░реЛрд╕реЗрд╕ рдирд╣реАрдВ рдХрд░ рд╕рдХреЗред
        
        *рдХрд╛рд░рдг:* {{payment_error}}
        
        рдЪрд┐рдВрддрд╛ рди рдХрд░реЗрдВ, рдЖрдкрдХреЗ рдЦрд╛рддреЗ рд╕реЗ рдХреЛрдИ рд░рд╛рд╢рд┐ рдирд╣реАрдВ рдХрд╛рдЯреА рдЧрдИ рд╣реИред
        
        рдХреНрдпрд╛ рдЖрдк рдЪрд╛рд╣реЗрдВрдЧреЗ:
        1. ЁЯФД рдлрд┐рд░ рд╕реЗ рдкреНрд░рдпрд╛рд╕ рдХрд░реЗрдВ
        2. ЁЯТ│ рджреВрд╕рд░реА рднреБрдЧрддрд╛рди рд╡рд┐рдзрд┐ рдХрд╛ рдЙрдкрдпреЛрдЧ рдХрд░реЗрдВ
        3. тЭМ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░реЗрдВ
      mr: |
        тЭМ *рдкреЗрдореЗрдВрдЯ рдЕрдпрд╢рд╕реНрд╡реА*
        
        рдСрд░реНрдбрд░ #{{order_id}} рд╕рд╛рдареА рддреБрдордЪреЗ рдкреЗрдореЗрдВрдЯ рдкреНрд░рдХреНрд░рд┐рдпрд╛ рдХрд░рддрд╛ рдЖрд▓реЗ рдирд╛рд╣реА.
        
        *рдХрд╛рд░рдг:* {{payment_error}}
        
        рдХрд╛рд│рдЬреА рдХрд░реВ рдирдХрд╛, рддреБрдордЪреНрдпрд╛ рдЦрд╛рддреНрдпрд╛рддреВрди рдХреЛрдгрддреАрд╣реА рд░рдХреНрдХрдо рдХрд╛рдкрд▓реА рдЧреЗрд▓реА рдирд╛рд╣реА.
        
        рддреБрдореНрд╣рд╛рд▓рд╛:
        1. ЁЯФД рдкреБрдиреНрд╣рд╛ рдкреНрд░рдпрддреНрди рдХрд░рд╛рдпрдЪрд╛ рдЖрд╣реЗ рдХрд╛
        2. ЁЯТ│ рд╡реЗрдЧрд│реА рдкреЗрдореЗрдВрдЯ рдкрджреНрдзрдд рд╡рд╛рдкрд░рд╛рдпрдЪреА рдЖрд╣реЗ рдХрд╛
        3. тЭМ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░рд╛рдпрдЪрд╛ рдЖрд╣реЗ рдХрд╛
    next: wait_payment_retry

  - id: wait_payment_retry
    type: input
    input_type: text
    next: process_retry_choice

  - id: process_retry_choice
    type: condition
    conditions:
      - condition: '{{input}} == "1"'
        next: retry_payment
      - condition: '{{input}} == "2"'
        next: change_payment_method
      - condition: '{{input}} == "3"'
        next: cancel_pending_order
    default: retry_payment

  - id: retry_payment
    type: action
    action: generate_payment_link
    params:
      order_id: '{{order_id}}'
      amount: '{{order_details.total}}'
    outputs:
      payment_link: payment_link
    next: send_retry_link

  - id: send_retry_link
    type: message
    message:
      en: "ЁЯФЧ Here's your payment link:\n\n{{payment_link}}\n\nThis link is valid for 15 minutes."
      hi: "ЁЯФЧ рдпрд╣рд╛рдВ рдЖрдкрдХрд╛ рднреБрдЧрддрд╛рди рд▓рд┐рдВрдХ рд╣реИ:\n\n{{payment_link}}\n\nрдпрд╣ рд▓рд┐рдВрдХ 15 рдорд┐рдирдЯ рдХреЗ рд▓рд┐рдП рд╡реИрдз рд╣реИред"
      mr: "ЁЯФЧ рд╣реЗ рддреБрдордЪреЗ рдкреЗрдореЗрдВрдЯ рд▓рд┐рдВрдХ рдЖрд╣реЗ:\n\n{{payment_link}}\n\nрд╣реА рд▓рд┐рдВрдХ 15 рдорд┐рдирд┐рдЯрд╛рдВрд╕рд╛рдареА рд╡реИрдз рдЖрд╣реЗ."
    next: end_flow

  - id: change_payment_method
    type: flow_transfer
    target_flow: payment_method_selection
    params:
      order_id: '{{order_id}}'

  - id: cancel_pending_order
    type: action
    action: php_api
    params:
      action: cancel_pending_order
      order_id: '{{order_id}}'
    next: order_cancelled_message

  - id: order_cancelled_message
    type: message
    message:
      en: "Your order has been cancelled. Feel free to order again anytime! ЁЯЩП"
      hi: "рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░ рджрд┐рдпрд╛ рдЧрдпрд╛ рд╣реИред рдХрднреА рднреА рдлрд┐рд░ рд╕реЗ рдСрд░реНрдбрд░ рдХрд░реЗрдВ! ЁЯЩП"
      mr: "рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХреЗрд▓рд╛ рдЖрд╣реЗ. рдХрдзреАрд╣реА рдкреБрдиреНрд╣рд╛ рдСрд░реНрдбрд░ рдХрд░рд╛! ЁЯЩП"
    next: end_flow

  # Payment Pending Flow
  - id: payment_pending
    type: message
    message:
      en: "тП│ Your payment is being processed. Please wait a moment...\n\nWe'll notify you once it's confirmed."
      hi: "тП│ рдЖрдкрдХрд╛ рднреБрдЧрддрд╛рди рдкреНрд░реЛрд╕реЗрд╕ рд╣реЛ рд░рд╣рд╛ рд╣реИред рдХреГрдкрдпрд╛ рдХреБрдЫ рдХреНрд╖рдг рдкреНрд░рддреАрдХреНрд╖рд╛ рдХрд░реЗрдВ...\n\nрдкреБрд╖реНрдЯрд┐ рд╣реЛрддреЗ рд╣реА рд╣рдо рдЖрдкрдХреЛ рд╕реВрдЪрд┐рдд рдХрд░реЗрдВрдЧреЗред"
      mr: "тП│ рддреБрдордЪреЗ рдкреЗрдореЗрдВрдЯ рдкреНрд░рдХреНрд░рд┐рдпрд╛ рд╣реЛрдд рдЖрд╣реЗ. рдХреГрдкрдпрд╛ рдереЛрдбреА рд╡рд╛рдЯ рдкрд╣рд╛...\n\nрдкреБрд╖реНрдЯреА рд╣реЛрддрд╛рдЪ рдЖрдореНрд╣реА рддреБрдореНрд╣рд╛рд▓рд╛ рдХрд│рд╡реВ."
    next: end_flow

  - id: end_flow
    type: end

# Proactive notifications (triggered by webhook)
proactive_notifications:
  # Order confirmed by vendor
  - trigger: order_confirmed
    message:
      en: |
        ЁЯОЙ *Great news!*
        
        {{vendor_name}} has confirmed your order #{{order_id}}!
        
        тП▒я╕П *Preparation Time:* {{processing_time}} minutes
        
        We'll update you when it's ready for delivery.
      hi: |
        ЁЯОЙ *рдЕрдЪреНрдЫреА рдЦрдмрд░!*
        
        {{vendor_name}} рдиреЗ рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ #{{order_id}} рдХрдиреНрдлрд░реНрдо рдХрд░ рджрд┐рдпрд╛ рд╣реИ!
        
        тП▒я╕П *рддреИрдпрд╛рд░реА рдХрд╛ рд╕рдордп:* {{processing_time}} рдорд┐рдирдЯ
        
        рдбрд┐рд▓реАрд╡рд░реА рдХреЗ рд▓рд┐рдП рддреИрдпрд╛рд░ рд╣реЛрдиреЗ рдкрд░ рд╣рдо рдЖрдкрдХреЛ рдЕрдкрдбреЗрдЯ рдХрд░реЗрдВрдЧреЗред
      mr: |
        ЁЯОЙ *рдЪрд╛рдВрдЧрд▓реА рдмрд╛рддрдореА!*
        
        {{vendor_name}} рдиреЗ рддреБрдордЪрд╛ рдСрд░реНрдбрд░ #{{order_id}} рдкреБрд╖реНрдЯреА рдХреЗрд▓рд╛ рдЖрд╣реЗ!
        
        тП▒я╕П *рддрдпрд╛рд░реАрдЪрд╛ рд╡реЗрд│:* {{processing_time}} рдорд┐рдирд┐рдЯреЗ
        
        рдбрд┐рд▓рд┐рд╡реНрд╣рд░реАрд╕рд╛рдареА рддрдпрд╛рд░ рдЭрд╛рд▓реНрдпрд╛рд╡рд░ рдЖрдореНрд╣реА рддреБрдореНрд╣рд╛рд▓рд╛ рдЕрдкрдбреЗрдЯ рдХрд░реВ.

  # Order ready for delivery
  - trigger: order_ready
    message:
      en: |
        ЁЯН│ *Your order is ready!*
        
        Order #{{order_id}} from {{vendor_name}} is packed and ready.
        
        ЁЯЪ┤ Finding a delivery partner...
      hi: |
        ЁЯН│ *рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рддреИрдпрд╛рд░ рд╣реИ!*
        
        {{vendor_name}} рд╕реЗ рдСрд░реНрдбрд░ #{{order_id}} рдкреИрдХ рд╣реЛ рдЧрдпрд╛ рд╣реИ рдФрд░ рддреИрдпрд╛рд░ рд╣реИред
        
        ЁЯЪ┤ рдбрд┐рд▓реАрд╡рд░реА рдкрд╛рд░реНрдЯрдирд░ рдвреВрдВрдв рд░рд╣реЗ рд╣реИрдВ...
      mr: |
        ЁЯН│ *рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рддрдпрд╛рд░ рдЖрд╣реЗ!*
        
        {{vendor_name}} рдХрдбреВрди рдСрд░реНрдбрд░ #{{order_id}} рдкреЕрдХ рдЭрд╛рд▓рд╛ рдЖрд╣реЗ рдЖрдгрд┐ рддрдпрд╛рд░ рдЖрд╣реЗ.
        
        ЁЯЪ┤ рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрд╛рд░реНрдЯрдирд░ рд╢реЛрдзрдд рдЖрд╣реЛрдд...

  # Delivery partner assigned
  - trigger: delivery_assigned
    message:
      en: |
        ЁЯЪ┤ *Delivery Partner Assigned!*
        
        *{{delivery_man_name}}* is on the way to pick up your order.
        
        ЁЯУЮ Contact: {{delivery_man_phone}}
        
        ЁЯУН Track live: {{tracking_link}}
      hi: |
        ЁЯЪ┤ *рдбрд┐рд▓реАрд╡рд░реА рдкрд╛рд░реНрдЯрдирд░ рдЕрд╕рд╛рдЗрди!*
        
        *{{delivery_man_name}}* рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рд▓реЗрдиреЗ рдЬрд╛ рд░рд╣реЗ рд╣реИрдВред
        
        ЁЯУЮ рд╕рдВрдкрд░реНрдХ: {{delivery_man_phone}}
        
        ЁЯУН рд▓рд╛рдЗрд╡ рдЯреНрд░реИрдХ рдХрд░реЗрдВ: {{tracking_link}}
      mr: |
        ЁЯЪ┤ *рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрд╛рд░реНрдЯрдирд░ рдирд┐рдпреБрдХреНрдд!*
        
        *{{delivery_man_name}}* рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рдШреЗрдгреНрдпрд╛рд╕рд╛рдареА рдорд╛рд░реНрдЧрд╛рд╡рд░ рдЖрд╣реЗ.
        
        ЁЯУЮ рд╕рдВрдкрд░реНрдХ: {{delivery_man_phone}}
        
        ЁЯУН рд▓рд╛рдЗрд╡реНрд╣ рдЯреНрд░реЕрдХ рдХрд░рд╛: {{tracking_link}}

  # Order picked up
  - trigger: order_picked_up
    message:
      en: |
        ЁЯЪ┤ *On the way!*
        
        {{delivery_man_name}} has picked up your order and is heading to you.
        
        тП▒я╕П *ETA:* {{eta_minutes}} minutes
        
        ЁЯУН Track live: {{tracking_link}}
      hi: |
        ЁЯЪ┤ *рд░рд╛рд╕реНрддреЗ рдореЗрдВ!*
        
        {{delivery_man_name}} рдиреЗ рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рдЙрдард╛ рд▓рд┐рдпрд╛ рд╣реИ рдФрд░ рдЖрдкрдХреА рдУрд░ рдЖ рд░рд╣реЗ рд╣реИрдВред
        
        тП▒я╕П *рдЕрдиреБрдорд╛рдирд┐рдд рд╕рдордп:* {{eta_minutes}} рдорд┐рдирдЯ
        
        ЁЯУН рд▓рд╛рдЗрд╡ рдЯреНрд░реИрдХ рдХрд░реЗрдВ: {{tracking_link}}
      mr: |
        ЁЯЪ┤ *рдорд╛рд░реНрдЧрд╛рд╡рд░!*
        
        {{delivery_man_name}} рдиреЗ рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рдЙрдЪрд▓рд▓рд╛ рдЖрд╣реЗ рдЖрдгрд┐ рддреБрдордЪреНрдпрд╛рдХрдбреЗ рдпреЗрдд рдЖрд╣реЗ.
        
        тП▒я╕П *рдЕрдВрджрд╛рдЬрд┐рдд рд╡реЗрд│:* {{eta_minutes}} рдорд┐рдирд┐рдЯреЗ
        
        ЁЯУН рд▓рд╛рдЗрд╡реНрд╣ рдЯреНрд░реЕрдХ рдХрд░рд╛: {{tracking_link}}

  # Order delivered
  - trigger: order_delivered
    message:
      en: |
        тЬЕ *Order Delivered!*
        
        Your order #{{order_id}} has been delivered.
        
        Enjoy your meal! ЁЯН╜я╕П
        
        тнР Please rate your experience:
        {{feedback_link}}
        
        Thank you for ordering with Mangwale! ЁЯЩП
      hi: |
        тЬЕ *рдСрд░реНрдбрд░ рдбрд┐рд▓реАрд╡рд░ рд╣реЛ рдЧрдпрд╛!*
        
        рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ #{{order_id}} рдбрд┐рд▓реАрд╡рд░ рд╣реЛ рдЧрдпрд╛ рд╣реИред
        
        рдЕрдкрдиреЗ рднреЛрдЬрди рдХрд╛ рдЖрдирдВрдж рд▓реЗрдВ! ЁЯН╜я╕П
        
        тнР рдХреГрдкрдпрд╛ рдЕрдкрдирд╛ рдЕрдиреБрднрд╡ рд░реЗрдЯ рдХрд░реЗрдВ:
        {{feedback_link}}
        
        Mangwale рдХреЗ рд╕рд╛рде рдСрд░реНрдбрд░ рдХрд░рдиреЗ рдХреЗ рд▓рд┐рдП рдзрдиреНрдпрд╡рд╛рдж! ЁЯЩП
      mr: |
        тЬЕ *рдСрд░реНрдбрд░ рдбрд┐рд▓рд┐рд╡реНрд╣рд░ рдЭрд╛рд▓рд╛!*
        
        рддреБрдордЪрд╛ рдСрд░реНрдбрд░ #{{order_id}} рдбрд┐рд▓рд┐рд╡реНрд╣рд░ рдЭрд╛рд▓рд╛ рдЖрд╣реЗ.
        
        рддреБрдордЪреНрдпрд╛ рдЬреЗрд╡рдгрд╛рдЪрд╛ рдЖрдирдВрдж рдШреНрдпрд╛! ЁЯН╜я╕П
        
        тнР рдХреГрдкрдпрд╛ рддреБрдордЪрд╛ рдЕрдиреБрднрд╡ рд░реЗрдЯ рдХрд░рд╛:
        {{feedback_link}}
        
        Mangwale рд╕реЛрдмрдд рдСрд░реНрдбрд░ рдХреЗрд▓реНрдпрд╛рдмрджреНрджрд▓ рдзрдиреНрдпрд╡рд╛рдж! ЁЯЩП
