# Customer Order Status Flow (v1)
# Handles order tracking, status updates, and proactive notifications

id: customer_order_status_v1
name: Customer Order Status
version: '1.0'
description: Track orders and receive status updates
enabled: true
finalStates: [end_flow]

triggers:
  - type: intent
    intents: [track_order, order_status, where_is_my_order, check_order]
  - type: message
    patterns:
      - 'track'
      - 'order.*status'
      - 'where.*order'
      - 'kahan.*order'
      - 'mera.*order'
      - 'my order'

variables:
  order_id: ''
  order_status: ''
  order_details: null
  eta_minutes: 0
  delivery_man_name: ''
  delivery_man_phone: ''
  tracking_link: ''

nodes:
  # Entry - check if user has active orders
  - id: check_active_orders
    type: action
    action: php_api
    params:
      action: get_customer_orders
      token: '{{session.auth_token}}'
      status: active
    outputs:
      orders: orders
      has_active_orders: has_active_orders
    next: check_orders_exist

  - id: check_orders_exist
    type: condition
    conditions:
      - condition: '{{has_active_orders}} == false'
        next: no_active_orders
      - condition: 'length({{orders}}) == 1'
        next: show_single_order
      - condition: 'length({{orders}}) > 1'
        next: list_active_orders
    default: no_active_orders

  # No active orders
  - id: no_active_orders
    type: message
    message:
      en: "You don't have any active orders right now. ЁЯУн\n\nWould you like to:\n1. ЁЯЫТ Place a new order\n2. ЁЯУЬ View order history"
      hi: "рдЕрднреА рдЖрдкрдХреЗ рдкрд╛рд╕ рдХреЛрдИ рд╕рдХреНрд░рд┐рдп рдСрд░реНрдбрд░ рдирд╣реАрдВ рд╣реИред ЁЯУн\n\nрдХреНрдпрд╛ рдЖрдк:\n1. ЁЯЫТ рдирдпрд╛ рдСрд░реНрдбрд░ рджреЗрдВ\n2. ЁЯУЬ рдСрд░реНрдбрд░ рдЗрддрд┐рд╣рд╛рд╕ рджреЗрдЦреЗрдВ"
      mr: "рд╕рдзреНрдпрд╛ рддреБрдордЪреНрдпрд╛рдХрдбреЗ рдХреЛрдгрддреЗрд╣реА рд╕рдХреНрд░рд┐рдп рдСрд░реНрдбрд░ рдирд╛рд╣реАрдд. ЁЯУн\n\nрддреБрдореНрд╣рд╛рд▓рд╛:\n1. ЁЯЫТ рдирд╡реАрди рдСрд░реНрдбрд░ рджреНрдпрд╛рдпрдЪреЗ рдЖрд╣реЗ рдХрд╛\n2. ЁЯУЬ рдСрд░реНрдбрд░ рдЗрддрд┐рд╣рд╛рд╕ рдкрд╣рд╛"
    next: wait_for_order_choice

  # Show single order status
  - id: show_single_order
    type: action
    action: get_order_status_details
    params:
      order_id: '{{orders[0].id}}'
      token: '{{session.auth_token}}'
    outputs:
      order_details: order_details
      eta_minutes: eta_minutes
      delivery_man: delivery_man
    next: display_order_status

  # List multiple active orders
  - id: list_active_orders
    type: message
    message:
      en: "You have {{length(orders)}} active orders:\n\n{{#each orders}}{{@index+1}}. Order #{{this.order_id}} - {{this.status_display}}\n   {{this.store_name}} - тВ╣{{this.total}}\n\n{{/each}}Reply with the number to track that order."
      hi: "рдЖрдкрдХреЗ {{length(orders)}} рд╕рдХреНрд░рд┐рдп рдСрд░реНрдбрд░ рд╣реИрдВ:\n\n{{#each orders}}{{@index+1}}. рдСрд░реНрдбрд░ #{{this.order_id}} - {{this.status_display}}\n   {{this.store_name}} - тВ╣{{this.total}}\n\n{{/each}}рдЙрд╕ рдСрд░реНрдбрд░ рдХреЛ рдЯреНрд░реИрдХ рдХрд░рдиреЗ рдХреЗ рд▓рд┐рдП рдирдВрдмрд░ рднреЗрдЬреЗрдВред"
      mr: "рддреБрдордЪреЗ {{length(orders)}} рд╕рдХреНрд░рд┐рдп рдСрд░реНрдбрд░ рдЖрд╣реЗрдд:\n\n{{#each orders}}{{@index+1}}. рдСрд░реНрдбрд░ #{{this.order_id}} - {{this.status_display}}\n   {{this.store_name}} - тВ╣{{this.total}}\n\n{{/each}}рддреНрдпрд╛ рдСрд░реНрдбрд░рдЪрд╛ рдорд╛рдЧреЛрд╡рд╛ рдШреЗрдгреНрдпрд╛рд╕рд╛рдареА рдХреНрд░рдорд╛рдВрдХ рдкрд╛рдард╡рд╛."
    next: wait_for_order_selection

  - id: wait_for_order_selection
    type: input
    input_type: text
    validation:
      pattern: '^\d+$'
    next: get_selected_order_details

  - id: get_selected_order_details
    type: action
    action: get_order_status_details
    params:
      order_id: '{{orders[input-1].id}}'
      token: '{{session.auth_token}}'
    outputs:
      order_details: order_details
      eta_minutes: eta_minutes
      delivery_man: delivery_man
    next: display_order_status

  # Display detailed order status
  - id: display_order_status
    type: message
    message:
      en: |
        ЁЯУж *Order #{{order_details.order_id}}*
        
        *Status:* {{order_details.status_emoji}} {{order_details.status_display}}
        
        *From:* {{order_details.store_name}}
        *Items:* {{order_details.items_summary}}
        *Total:* тВ╣{{order_details.total}}
        
        {{#if eta_minutes}}
        тП▒я╕П *Estimated Time:* {{eta_minutes}} minutes
        {{/if}}
        
        {{#if delivery_man}}
        ЁЯЪ┤ *Delivery Partner:* {{delivery_man.name}}
        ЁЯУЮ Contact: {{delivery_man.phone}}
        {{/if}}
        
        {{#if order_details.tracking_link}}
        ЁЯУН *Live Tracking:* {{order_details.tracking_link}}
        {{/if}}
        
        ---
        Reply:
        тАв *CALL* - Call delivery partner
        тАв *CANCEL* - Cancel order (if allowed)
        тАв *HELP* - Contact support
      hi: |
        ЁЯУж *рдСрд░реНрдбрд░ #{{order_details.order_id}}*
        
        *рд╕реНрдерд┐рддрд┐:* {{order_details.status_emoji}} {{order_details.status_display}}
        
        *рд╕реЗ:* {{order_details.store_name}}
        *рдЖрдЗрдЯрдо:* {{order_details.items_summary}}
        *рдХреБрд▓:* тВ╣{{order_details.total}}
        
        {{#if eta_minutes}}
        тП▒я╕П *рдЕрдиреБрдорд╛рдирд┐рдд рд╕рдордп:* {{eta_minutes}} рдорд┐рдирдЯ
        {{/if}}
        
        {{#if delivery_man}}
        ЁЯЪ┤ *рдбрд┐рд▓реАрд╡рд░реА рдкрд╛рд░реНрдЯрдирд░:* {{delivery_man.name}}
        ЁЯУЮ рд╕рдВрдкрд░реНрдХ: {{delivery_man.phone}}
        {{/if}}
        
        {{#if order_details.tracking_link}}
        ЁЯУН *рд▓рд╛рдЗрд╡ рдЯреНрд░реИрдХрд┐рдВрдЧ:* {{order_details.tracking_link}}
        {{/if}}
        
        ---
        рдЬрд╡рд╛рдм рджреЗрдВ:
        тАв *CALL* - рдбрд┐рд▓реАрд╡рд░реА рдкрд╛рд░реНрдЯрдирд░ рдХреЛ рдХреЙрд▓ рдХрд░реЗрдВ
        тАв *CANCEL* - рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░реЗрдВ (рдпрджрд┐ рдЕрдиреБрдорддрд┐ рд╣реЛ)
        тАв *HELP* - рд╕рд╣рд╛рдпрддрд╛ рд╕реЗ рд╕рдВрдкрд░реНрдХ рдХрд░реЗрдВ
      mr: |
        ЁЯУж *рдСрд░реНрдбрд░ #{{order_details.order_id}}*
        
        *рд╕реНрдерд┐рддреА:* {{order_details.status_emoji}} {{order_details.status_display}}
        
        *рдкрд╛рд╕реВрди:* {{order_details.store_name}}
        *рдЖрдпрдЯрдо:* {{order_details.items_summary}}
        *рдПрдХреВрдг:* тВ╣{{order_details.total}}
        
        {{#if eta_minutes}}
        тП▒я╕П *рдЕрдВрджрд╛рдЬрд┐рдд рд╡реЗрд│:* {{eta_minutes}} рдорд┐рдирд┐рдЯреЗ
        {{/if}}
        
        {{#if delivery_man}}
        ЁЯЪ┤ *рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрд╛рд░реНрдЯрдирд░:* {{delivery_man.name}}
        ЁЯУЮ рд╕рдВрдкрд░реНрдХ: {{delivery_man.phone}}
        {{/if}}
        
        {{#if order_details.tracking_link}}
        ЁЯУН *рд▓рд╛рдЗрд╡реНрд╣ рдЯреНрд░реЕрдХрд┐рдВрдЧ:* {{order_details.tracking_link}}
        {{/if}}
        
        ---
        рдЙрддреНрддрд░ рджреНрдпрд╛:
        тАв *CALL* - рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрд╛рд░реНрдЯрдирд░рд▓рд╛ рдХреЙрд▓ рдХрд░рд╛
        тАв *CANCEL* - рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░рд╛ (рдкрд░рд╡рд╛рдирдЧреА рдЕрд╕рд▓реНрдпрд╛рд╕)
        тАв *HELP* - рд╕рдорд░реНрдердирд╛рд╢реА рд╕рдВрдкрд░реНрдХ рд╕рд╛рдзрд╛
    next: wait_for_action

  # Wait for user action
  - id: wait_for_action
    type: input
    input_type: text
    next: process_action

  - id: process_action
    type: condition
    conditions:
      - condition: 'match({{input}}, "^(call|рдХреЙрд▓)$", "i")'
        next: initiate_call_delivery
      - condition: 'match({{input}}, "^(cancel|рд░рджреНрдж)$", "i")'
        next: check_cancel_allowed
      - condition: 'match({{input}}, "^(help|рдорджрдж|рд╕рд╣рд╛рдпрддрд╛)$", "i")'
        next: transfer_to_support
    default: end_flow

  # Call delivery partner
  - id: initiate_call_delivery
    type: condition
    conditions:
      - condition: '{{delivery_man}} != null'
        next: show_delivery_contact
    default: no_delivery_assigned

  - id: show_delivery_contact
    type: message
    message:
      en: "ЁЯУЮ Your delivery partner's number:\n\n*{{delivery_man.name}}*\n{{delivery_man.phone}}\n\nYou can call them directly or tap the number above."
      hi: "ЁЯУЮ рдЖрдкрдХреЗ рдбрд┐рд▓реАрд╡рд░реА рдкрд╛рд░реНрдЯрдирд░ рдХрд╛ рдирдВрдмрд░:\n\n*{{delivery_man.name}}*\n{{delivery_man.phone}}\n\nрдЖрдк рдЙрдиреНрд╣реЗрдВ рд╕реАрдзреЗ рдХреЙрд▓ рдХрд░ рд╕рдХрддреЗ рд╣реИрдВред"
      mr: "ЁЯУЮ рддреБрдордЪреНрдпрд╛ рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрд╛рд░реНрдЯрдирд░рдЪрд╛ рдирдВрдмрд░:\n\n*{{delivery_man.name}}*\n{{delivery_man.phone}}\n\nрддреБрдореНрд╣реА рддреНрдпрд╛рдВрдирд╛ рдереЗрдЯ рдХреЙрд▓ рдХрд░реВ рд╢рдХрддрд╛."
    next: end_flow

  - id: no_delivery_assigned
    type: message
    message:
      en: "No delivery partner has been assigned yet. Your order is still being prepared. ЁЯН│"
      hi: "рдЕрднреА рддрдХ рдХреЛрдИ рдбрд┐рд▓реАрд╡рд░реА рдкрд╛рд░реНрдЯрдирд░ рдирд┐рдпреБрдХреНрдд рдирд╣реАрдВ рдХрд┐рдпрд╛ рдЧрдпрд╛ рд╣реИред рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рдЕрднреА рддреИрдпрд╛рд░ рд╣реЛ рд░рд╣рд╛ рд╣реИред ЁЯН│"
      mr: "рдЕрдЬреВрди рдХреЛрдгрддрд╛рд╣реА рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рдкрд╛рд░реНрдЯрдирд░ рдирд┐рдпреБрдХреНрдд рдХреЗрд▓реЗрд▓рд╛ рдирд╛рд╣реА. рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рдЕрдЬреВрди рддрдпрд╛рд░ рд╣реЛрдд рдЖрд╣реЗ. ЁЯН│"
    next: end_flow

  # Check if cancel is allowed
  - id: check_cancel_allowed
    type: action
    action: check_cancel_eligibility
    params:
      order_id: '{{order_details.id}}'
      token: '{{session.auth_token}}'
    outputs:
      can_cancel: can_cancel
      cancel_reason: cancel_reason
    next: process_cancel_check

  - id: process_cancel_check
    type: condition
    conditions:
      - condition: '{{can_cancel}} == true'
        next: confirm_cancel
    default: cancel_not_allowed

  - id: cancel_not_allowed
    type: message
    message:
      en: "тЭМ Sorry, this order cannot be canceled.\n\n*Reason:* {{cancel_reason}}\n\nIf you have concerns, please contact support."
      hi: "тЭМ рдХреНрд╖рдорд╛ рдХрд░реЗрдВ, рдпрд╣ рдСрд░реНрдбрд░ рд░рджреНрдж рдирд╣реАрдВ рдХрд┐рдпрд╛ рдЬрд╛ рд╕рдХрддрд╛ред\n\n*рдХрд╛рд░рдг:* {{cancel_reason}}\n\nрдХрд┐рд╕реА рд╕рдорд╕реНрдпрд╛ рдХреЗ рд▓рд┐рдП рдХреГрдкрдпрд╛ рд╕рд╣рд╛рдпрддрд╛ рд╕реЗ рд╕рдВрдкрд░реНрдХ рдХрд░реЗрдВред"
      mr: "тЭМ рдорд╛рдл рдХрд░рд╛, рд╣рд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░рддрд╛ рдпреЗрдгрд╛рд░ рдирд╛рд╣реА.\n\n*рдХрд╛рд░рдг:* {{cancel_reason}}\n\nрд╕рдорд╕реНрдпрд╛ рдЕрд╕рд▓реНрдпрд╛рд╕ рдХреГрдкрдпрд╛ рд╕рдорд░реНрдердирд╛рд╢реА рд╕рдВрдкрд░реНрдХ рд╕рд╛рдзрд╛."
    next: end_flow

  - id: confirm_cancel
    type: message
    message:
      en: "Are you sure you want to cancel this order?\n\n*Order #{{order_details.order_id}}*\n*Total:* тВ╣{{order_details.total}}\n\nReply *YES* to confirm or *NO* to keep the order."
      hi: "рдХреНрдпрд╛ рдЖрдк рд╡рд╛рдХрдИ рдЗрд╕ рдСрд░реНрдбрд░ рдХреЛ рд░рджреНрдж рдХрд░рдирд╛ рдЪрд╛рд╣рддреЗ рд╣реИрдВ?\n\n*рдСрд░реНрдбрд░ #{{order_details.order_id}}*\n*рдХреБрд▓:* тВ╣{{order_details.total}}\n\nрдкреБрд╖реНрдЯрд┐ рдХреЗ рд▓рд┐рдП *YES* рдпрд╛ рд░рдЦрдиреЗ рдХреЗ рд▓рд┐рдП *NO* рднреЗрдЬреЗрдВред"
      mr: "рддреБрдореНрд╣рд╛рд▓рд╛ рдЦрд░реЛрдЦрд░ рд╣рд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░рд╛рдпрдЪрд╛ рдЖрд╣реЗ рдХрд╛?\n\n*рдСрд░реНрдбрд░ #{{order_details.order_id}}*\n*рдПрдХреВрдг:* тВ╣{{order_details.total}}\n\nрдкреБрд╖реНрдЯреАрд╕рд╛рдареА *YES* рдХрд┐рдВрд╡рд╛ рдареЗрд╡рдгреНрдпрд╛рд╕рд╛рдареА *NO* рдкрд╛рдард╡рд╛."
    next: wait_cancel_confirmation

  - id: wait_cancel_confirmation
    type: input
    input_type: text
    next: process_cancel_confirmation

  - id: process_cancel_confirmation
    type: condition
    conditions:
      - condition: 'match({{input}}, "^(yes|рд╣рд╛рдВ|рд╣реЛрдп)$", "i")'
        next: execute_cancel
    default: cancel_aborted

  - id: execute_cancel
    type: action
    action: php_api
    params:
      action: cancel_order
      order_id: '{{order_details.id}}'
      token: '{{session.auth_token}}'
      reason: 'Customer requested cancellation via WhatsApp'
    outputs:
      cancel_success: success
      refund_info: refund_info
    next: show_cancel_result

  - id: show_cancel_result
    type: condition
    conditions:
      - condition: '{{cancel_success}} == true'
        next: cancel_success_message
    default: cancel_failed_message

  - id: cancel_success_message
    type: message
    message:
      en: "тЬЕ Your order has been canceled.\n\n{{#if refund_info}}*Refund:* тВ╣{{refund_info.amount}} will be credited to your {{refund_info.method}} within {{refund_info.days}} days.{{/if}}\n\nWe hope to serve you again soon! ЁЯЩП"
      hi: "тЬЕ рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░ рджрд┐рдпрд╛ рдЧрдпрд╛ рд╣реИред\n\n{{#if refund_info}}*рд░рд┐рдлрдВрдб:* тВ╣{{refund_info.amount}} {{refund_info.days}} рджрд┐рдиреЛрдВ рдореЗрдВ рдЖрдкрдХреЗ {{refund_info.method}} рдореЗрдВ рдХреНрд░реЗрдбрд┐рдЯ рд╣реЛрдЧрд╛ред{{/if}}\n\nрд╣рдореЗрдВ рдЙрдореНрдореАрдж рд╣реИ рдХрд┐ рдЬрд▓реНрдж рд╣реА рдЖрдкрдХреА рд╕реЗрд╡рд╛ рдХрд░реЗрдВрдЧреЗ! ЁЯЩП"
      mr: "тЬЕ рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХреЗрд▓рд╛ рдЖрд╣реЗ.\n\n{{#if refund_info}}*рдкрд░рддрд╛рд╡рд╛:* тВ╣{{refund_info.amount}} {{refund_info.days}} рджрд┐рд╡рд╕рд╛рдВрдд рддреБрдордЪреНрдпрд╛ {{refund_info.method}} рдордзреНрдпреЗ рдЬрдорд╛ рд╣реЛрдИрд▓.{{/if}}\n\nрдЖрдореНрд╣рд╛рд▓рд╛ рдЖрд╢рд╛ рдЖрд╣реЗ рдХреА рд▓рд╡рдХрд░рдЪ рддреБрдордЪреА рд╕реЗрд╡рд╛ рдХрд░реВ! ЁЯЩП"
    next: end_flow

  - id: cancel_failed_message
    type: message
    message:
      en: "тЭМ Sorry, we couldn't cancel your order. Please contact support for assistance."
      hi: "тЭМ рдХреНрд╖рдорд╛ рдХрд░реЗрдВ, рд╣рдо рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдирд╣реАрдВ рдХрд░ рд╕рдХреЗред рдХреГрдкрдпрд╛ рд╕рд╣рд╛рдпрддрд╛ рдХреЗ рд▓рд┐рдП рд╕рдкреЛрд░реНрдЯ рд╕реЗ рд╕рдВрдкрд░реНрдХ рдХрд░реЗрдВред"
      mr: "тЭМ рдорд╛рдл рдХрд░рд╛, рдЖрдореНрд╣реА рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рд░рджреНрдж рдХрд░реВ рд╢рдХрд▓реЛ рдирд╛рд╣реА. рдХреГрдкрдпрд╛ рдорджрддреАрд╕рд╛рдареА рд╕рдорд░реНрдердирд╛рд╢реА рд╕рдВрдкрд░реНрдХ рд╕рд╛рдзрд╛."
    next: transfer_to_support

  - id: cancel_aborted
    type: message
    message:
      en: "Okay, your order is still active. ЁЯСН"
      hi: "рдареАрдХ рд╣реИ, рдЖрдкрдХрд╛ рдСрд░реНрдбрд░ рдЕрднреА рднреА рд╕рдХреНрд░рд┐рдп рд╣реИред ЁЯСН"
      mr: "рдареАрдХ рдЖрд╣реЗ, рддреБрдордЪрд╛ рдСрд░реНрдбрд░ рдЕрдЬреВрдирд╣реА рд╕рдХреНрд░рд┐рдп рдЖрд╣реЗ. ЁЯСН"
    next: end_flow

  # Transfer to support
  - id: transfer_to_support
    type: flow_transfer
    target_flow: customer_support

  # Wait for order choice
  - id: wait_for_order_choice
    type: input
    input_type: text
    next: process_order_choice

  - id: process_order_choice
    type: condition
    conditions:
      - condition: '{{input}} == "1"'
        next: transfer_to_ordering
      - condition: '{{input}} == "2"'
        next: show_order_history
    default: end_flow

  - id: transfer_to_ordering
    type: flow_transfer
    target_flow: food_ordering

  - id: show_order_history
    type: action
    action: php_api
    params:
      action: get_customer_orders
      token: '{{session.auth_token}}'
      status: all
      limit: 5
    outputs:
      orders: past_orders
    next: display_history

  - id: display_history
    type: message
    message:
      en: "ЁЯУЬ *Your Recent Orders*\n\n{{#each past_orders}}{{@index+1}}. #{{this.order_id}} - {{this.status_display}}\n   {{this.store_name}} | тВ╣{{this.total}}\n   {{this.date}}\n\n{{/each}}"
      hi: "ЁЯУЬ *рдЖрдкрдХреЗ рд╣рд╛рд▓ рдХреЗ рдСрд░реНрдбрд░*\n\n{{#each past_orders}}{{@index+1}}. #{{this.order_id}} - {{this.status_display}}\n   {{this.store_name}} | тВ╣{{this.total}}\n   {{this.date}}\n\n{{/each}}"
      mr: "ЁЯУЬ *рддреБрдордЪреЗ рдЕрд▓реАрдХрдбреАрд▓ рдСрд░реНрдбрд░*\n\n{{#each past_orders}}{{@index+1}}. #{{this.order_id}} - {{this.status_display}}\n   {{this.store_name}} | тВ╣{{this.total}}\n   {{this.date}}\n\n{{/each}}"
    next: end_flow

  - id: end_flow
    type: end
