# User Type Detection Flow (v1)
# This flow runs at the start of every conversation to detect user type
# and route them to the appropriate flow (customer, vendor, or delivery man)

id: user_type_detection_v1
name: User Type Detection
version: '1.0'
description: Detect if user is customer, vendor, or delivery man based on phone number
enabled: true
finalStates: [transfer_to_vendor_flow, transfer_to_delivery_flow, transfer_to_customer_flow, transfer_to_registration]

# Trigger on any new conversation
triggers:
  - type: message
    pattern: '.*'
    conditions:
      - session.user_type_detected != true

# Variables to track
variables:
  phone: ''
  user_type: ''  # customer, vendor, delivery_man, new_user
  available_roles: []
  vendor_store_name: ''
  customer_name: ''
  delivery_man_name: ''
  has_active_work: false
  needs_role_selection: false

# Main flow
nodes:
  # Entry point - extract phone and detect type
  - id: detect_user_type
    type: action
    action: detect_user_type
    params:
      phone: '{{session.phone}}'
    outputs:
      user_type: user_type
      available_roles: available_roles
      vendor_data: vendor_data
      customer_data: customer_data
      delivery_data: delivery_data
      needs_role_selection: needs_role_selection
    next: check_role_count

  # Check if user has multiple roles
  - id: check_role_count
    type: condition
    conditions:
      - condition: '{{needs_role_selection}} == true'
        next: ask_role_selection
      - condition: '{{user_type}} == "vendor"'
        next: route_to_vendor
      - condition: '{{user_type}} == "delivery_man"'
        next: route_to_delivery
      - condition: '{{user_type}} == "customer"'
        next: route_to_customer
      - condition: '{{user_type}} == "new_user"'
        next: greet_new_user
    default: greet_new_user

  # Ask user to select role when multiple roles exist
  - id: ask_role_selection
    type: message
    message:
      en: |
        Hello! ЁЯСЛ I see you have multiple accounts with us.

        How would you like to continue today?

        {{#if is_customer}}1. ЁЯЫТ Order food as a customer{{/if}}
        {{#if is_vendor}}{{customer_option_num}}. ЁЯПк Manage my store ({{vendor_store_name}}){{/if}}
        {{#if is_delivery_man}}{{delivery_option_num}}. ЁЯЪ┤ Check my deliveries{{/if}}

        Please reply with the number of your choice.
      hi: |
        рдирдорд╕реНрддреЗ! ЁЯСЛ рдореБрдЭреЗ рджрд┐рдЦрддрд╛ рд╣реИ рдХрд┐ рдЖрдкрдХреЗ рдкрд╛рд╕ рд╣рдорд╛рд░реЗ рд╕рд╛рде рдХрдИ рдЦрд╛рддреЗ рд╣реИрдВред

        рдЖрдЬ рдЖрдк рдХреИрд╕реЗ рдЬрд╛рд░реА рд░рдЦрдирд╛ рдЪрд╛рд╣реЗрдВрдЧреЗ?

        {{#if is_customer}}1. ЁЯЫТ рдЧреНрд░рд╛рд╣рдХ рдХреЗ рд░реВрдк рдореЗрдВ рдЦрд╛рдирд╛ рдСрд░реНрдбрд░ рдХрд░реЗрдВ{{/if}}
        {{#if is_vendor}}{{customer_option_num}}. ЁЯПк рдореЗрд░реА рджреБрдХрд╛рди ({{vendor_store_name}}) рдкреНрд░рдмрдВрдзрд┐рдд рдХрд░реЗрдВ{{/if}}
        {{#if is_delivery_man}}{{delivery_option_num}}. ЁЯЪ┤ рдореЗрд░реА рдбрд┐рд▓реАрд╡рд░реА рджреЗрдЦреЗрдВ{{/if}}

        рдХреГрдкрдпрд╛ рдЕрдкрдиреА рдкрд╕рдВрдж рдХрд╛ рдирдВрдмрд░ рднреЗрдЬреЗрдВред
      mr: |
        рдирдорд╕реНрдХрд╛рд░! ЁЯСЛ рдорд▓рд╛ рджрд┐рд╕рддреЗ рдХреА рддреБрдордЪреНрдпрд╛рдХрдбреЗ рдЖрдордЪреНрдпрд╛рдХрдбреЗ рдЕрдиреЗрдХ рдЦрд╛рддреА рдЖрд╣реЗрдд.

        рдЖрдЬ рддреБрдореНрд╣реА рдХрд╕реЗ рдкреБрдвреЗ рдЬрд╛рдК рдЗрдЪреНрдЫрд┐рддрд╛?

        {{#if is_customer}}1. ЁЯЫТ рдЧреНрд░рд╛рд╣рдХ рдореНрд╣рдгреВрди рдЬреЗрд╡рдг рдСрд░реНрдбрд░ рдХрд░рд╛{{/if}}
        {{#if is_vendor}}{{customer_option_num}}. ЁЯПк рдорд╛рдЭреЗ рджреБрдХрд╛рди ({{vendor_store_name}}) рд╡реНрдпрд╡рд╕реНрдерд╛рдкрд┐рдд рдХрд░рд╛{{/if}}
        {{#if is_delivery_man}}{{delivery_option_num}}. ЁЯЪ┤ рдорд╛рдЭреНрдпрд╛ рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА рддрдкрд╛рд╕рд╛{{/if}}

        рдХреГрдкрдпрд╛ рддреБрдордЪреНрдпрд╛ рдирд┐рд╡рдбреАрдЪрд╛ рдХреНрд░рдорд╛рдВрдХ рдкрд╛рдард╡рд╛.
    next: wait_for_role_selection

  # Wait for user's role selection
  - id: wait_for_role_selection
    type: input
    input_type: text
    validation:
      pattern: '^[1-3]$'
      error_message:
        en: "Please reply with 1, 2, or 3 to select your role."
        hi: "рдХреГрдкрдпрд╛ рдЕрдкрдиреА рднреВрдорд┐рдХрд╛ рдЪреБрдирдиреЗ рдХреЗ рд▓рд┐рдП 1, 2 рдпрд╛ 3 рднреЗрдЬреЗрдВред"
        mr: "рдХреГрдкрдпрд╛ рддреБрдордЪреА рднреВрдорд┐рдХрд╛ рдирд┐рд╡рдбрдгреНрдпрд╛рд╕рд╛рдареА 1, 2 рдХрд┐рдВрд╡рд╛ 3 рдкрд╛рдард╡рд╛."
    next: process_role_selection

  # Process the selected role
  - id: process_role_selection
    type: action
    action: set_selected_role
    params:
      selection: '{{input}}'
      available_roles: '{{available_roles}}'
    outputs:
      selected_role: selected_role
    next: route_by_selection

  # Route based on selection
  - id: route_by_selection
    type: condition
    conditions:
      - condition: '{{selected_role}} == "vendor"'
        next: route_to_vendor
      - condition: '{{selected_role}} == "delivery_man"'
        next: route_to_delivery
      - condition: '{{selected_role}} == "customer"'
        next: route_to_customer
    default: route_to_customer

  # Route to vendor flow
  - id: route_to_vendor
    type: action
    action: set_session_context
    params:
      user_type: vendor
      vendor_id: '{{vendor_data.id}}'
      store_id: '{{vendor_data.storeId}}'
      store_name: '{{vendor_data.storeName}}'
      user_type_detected: true
    next: vendor_greeting

  - id: vendor_greeting
    type: message
    message:
      en: "Welcome back, {{vendor_store_name}}! ЁЯПк\n\nI can help you with:\nтАв ЁЯУж View new orders\nтАв тЬЕ Accept/reject orders\nтАв ЁЯУЬ Order history\nтАв ЁЯН╜я╕П Manage menu items\n\nWhat would you like to do?"
      hi: "рд╡рд╛рдкрд╕ рд╕реНрд╡рд╛рдЧрдд рд╣реИ, {{vendor_store_name}}! ЁЯПк\n\nрдореИрдВ рдЗрд╕рдореЗрдВ рдорджрдж рдХрд░ рд╕рдХрддрд╛ рд╣реВрдВ:\nтАв ЁЯУж рдирдП рдСрд░реНрдбрд░ рджреЗрдЦреЗрдВ\nтАв тЬЕ рдСрд░реНрдбрд░ рд╕реНрд╡реАрдХрд╛рд░/рдЕрд╕реНрд╡реАрдХрд╛рд░ рдХрд░реЗрдВ\nтАв ЁЯУЬ рдСрд░реНрдбрд░ рдЗрддрд┐рд╣рд╛рд╕\nтАв ЁЯН╜я╕П рдореЗрдиреВ рдЖрдЗрдЯрдо рдкреНрд░рдмрдВрдзрд┐рдд рдХрд░реЗрдВ\n\nрдЖрдк рдХреНрдпрд╛ рдХрд░рдирд╛ рдЪрд╛рд╣реЗрдВрдЧреЗ?"
      mr: "рдкреБрдиреНрд╣рд╛ рд╕реНрд╡рд╛рдЧрдд, {{vendor_store_name}}! ЁЯПк\n\nрдореА рдпрд╛рдд рдорджрдд рдХрд░реВ рд╢рдХрддреЛ:\nтАв ЁЯУж рдирд╡реАрди рдСрд░реНрдбрд░ рдкрд╣рд╛\nтАв тЬЕ рдСрд░реНрдбрд░ рд╕реНрд╡реАрдХрд╛рд░рд╛/рдирд╛рдХрд╛рд░рд╛\nтАв ЁЯУЬ рдСрд░реНрдбрд░ рдЗрддрд┐рд╣рд╛рд╕\nтАв ЁЯН╜я╕П рдореЗрдиреВ рдЖрдпрдЯрдо рд╡реНрдпрд╡рд╕реНрдерд╛рдкрд┐рдд рдХрд░рд╛\n\nрддреБрдореНрд╣рд╛рд▓рд╛ рдХрд╛рдп рдХрд░рд╛рдпрдЪреЗ рдЖрд╣реЗ?"
    next: transfer_to_vendor_flow

  - id: transfer_to_vendor_flow
    type: flow_transfer
    target_flow: vendor_orders_v1

  # Route to delivery man flow
  - id: route_to_delivery
    type: action
    action: set_session_context
    params:
      user_type: delivery_man
      delivery_man_id: '{{delivery_data.id}}'
      delivery_man_name: '{{delivery_data.name}}'
      user_type_detected: true
    next: delivery_greeting

  - id: delivery_greeting
    type: message
    message:
      en: "Hey {{delivery_man_name}}! ЁЯЪ┤\n\nI can help you with:\nтАв ЁЯУж Current deliveries\nтАв тЬЕ Accept new orders\nтАв ЁЯТ░ Today's earnings\nтАв ЁЯУН Update status\n\nWhat do you need?"
      hi: "рд╣реЗрдп {{delivery_man_name}}! ЁЯЪ┤\n\nрдореИрдВ рдЗрд╕рдореЗрдВ рдорджрдж рдХрд░ рд╕рдХрддрд╛ рд╣реВрдВ:\nтАв ЁЯУж рд╡рд░реНрддрдорд╛рди рдбрд┐рд▓реАрд╡рд░реА\nтАв тЬЕ рдирдП рдСрд░реНрдбрд░ рд╕реНрд╡реАрдХрд╛рд░ рдХрд░реЗрдВ\nтАв ЁЯТ░ рдЖрдЬ рдХреА рдХрдорд╛рдИ\nтАв ЁЯУН рд╕реНрдерд┐рддрд┐ рдЕрдкрдбреЗрдЯ рдХрд░реЗрдВ\n\nрдЖрдкрдХреЛ рдХреНрдпрд╛ рдЪрд╛рд╣рд┐рдП?"
      mr: "рдЕрд░реЗ {{delivery_man_name}}! ЁЯЪ┤\n\nрдореА рдпрд╛рдд рдорджрдд рдХрд░реВ рд╢рдХрддреЛ:\nтАв ЁЯУж рд╕рдзреНрдпрд╛рдЪреНрдпрд╛ рдбрд┐рд▓рд┐рд╡реНрд╣рд░реА\nтАв тЬЕ рдирд╡реАрди рдСрд░реНрдбрд░ рд╕реНрд╡реАрдХрд╛рд░рд╛\nтАв ЁЯТ░ рдЖрдЬрдЪреА рдХрдорд╛рдИ\nтАв ЁЯУН рд╕реНрдерд┐рддреА рдЕрдкрдбреЗрдЯ рдХрд░рд╛\n\nрддреБрдореНрд╣рд╛рд▓рд╛ рдХрд╛рдп рд╣рд╡реЗ?"
    next: transfer_to_delivery_flow

  - id: transfer_to_delivery_flow
    type: flow_transfer
    target_flow: delivery_orders_v1

  # Route to customer flow
  - id: route_to_customer
    type: action
    action: set_session_context
    params:
      user_type: customer
      customer_id: '{{customer_data.id}}'
      customer_name: '{{customer_data.name}}'
      user_type_detected: true
    next: customer_greeting

  - id: customer_greeting
    type: message
    message:
      en: "Hello {{customer_name}}! ЁЯСЛ\n\nWelcome to Mangwale!\n\nI can help you:\nЁЯНФ Order food\nЁЯУж Track your orders\nЁЯОБ Check rewards\nЁЯУН Manage addresses\n\nWhat would you like to do today?"
      hi: "рдирдорд╕реНрддреЗ {{customer_name}}! ЁЯСЛ\n\nMangwale рдореЗрдВ рдЖрдкрдХрд╛ рд╕реНрд╡рд╛рдЧрдд рд╣реИ!\n\nрдореИрдВ рдЖрдкрдХреА рдорджрдж рдХрд░ рд╕рдХрддрд╛ рд╣реВрдВ:\nЁЯНФ рдЦрд╛рдирд╛ рдСрд░реНрдбрд░ рдХрд░реЗрдВ\nЁЯУж рдЕрдкрдиреЗ рдСрд░реНрдбрд░ рдЯреНрд░реИрдХ рдХрд░реЗрдВ\nЁЯОБ рд░рд┐рд╡реЙрд░реНрдбреНрд╕ рджреЗрдЦреЗрдВ\nЁЯУН рдкрддреЗ рдкреНрд░рдмрдВрдзрд┐рдд рдХрд░реЗрдВ\n\nрдЖрдЬ рдЖрдк рдХреНрдпрд╛ рдХрд░рдирд╛ рдЪрд╛рд╣реЗрдВрдЧреЗ?"
      mr: "рдирдорд╕реНрдХрд╛рд░ {{customer_name}}! ЁЯСЛ\n\nMangwale рдордзреНрдпреЗ рдЖрдкрд▓реЗ рд╕реНрд╡рд╛рдЧрдд!\n\nрдореА рддреБрдореНрд╣рд╛рд▓рд╛ рдорджрдд рдХрд░реВ рд╢рдХрддреЛ:\nЁЯНФ рдЬреЗрд╡рдг рдСрд░реНрдбрд░ рдХрд░рд╛\nЁЯУж рддреБрдордЪреЗ рдСрд░реНрдбрд░ рдЯреНрд░реЕрдХ рдХрд░рд╛\nЁЯОБ рд░рд┐рд╡реЙрд░реНрдбреНрд╕ рддрдкрд╛рд╕рд╛\nЁЯУН рдкрддреНрддреЗ рд╡реНрдпрд╡рд╕реНрдерд╛рдкрд┐рдд рдХрд░рд╛\n\nрдЖрдЬ рддреБрдореНрд╣рд╛рд▓рд╛ рдХрд╛рдп рдХрд░рд╛рдпрдЪреЗ рдЖрд╣реЗ?"
    next: transfer_to_customer_flow

  - id: transfer_to_customer_flow
    type: flow_transfer
    target_flow: main_menu

  # Greet new user
  - id: greet_new_user
    type: action
    action: set_session_context
    params:
      user_type: new_user
      user_type_detected: true
    next: new_user_greeting

  - id: new_user_greeting
    type: message
    message:
      en: "Hello! ЁЯСЛ Welcome to Mangwale!\n\nI'm your AI assistant for food ordering.\n\nTo get started, please share your phone number for registration.\n\nOr you can:\nтАв Browse restaurants\nтАв Check our menu\nтАв Learn about our services"
      hi: "рдирдорд╕реНрддреЗ! ЁЯСЛ Mangwale рдореЗрдВ рдЖрдкрдХрд╛ рд╕реНрд╡рд╛рдЧрдд рд╣реИ!\n\nрдореИрдВ рдЦрд╛рдирд╛ рдСрд░реНрдбрд░ рдХрд░рдиреЗ рдХреЗ рд▓рд┐рдП рдЖрдкрдХрд╛ AI рд╕рд╣рд╛рдпрдХ рд╣реВрдВред\n\nрд╢реБрд░реВ рдХрд░рдиреЗ рдХреЗ рд▓рд┐рдП, рдХреГрдкрдпрд╛ рдкрдВрдЬреАрдХрд░рдг рдХреЗ рд▓рд┐рдП рдЕрдкрдирд╛ рдлреЛрди рдирдВрдмрд░ рд╕рд╛рдЭрд╛ рдХрд░реЗрдВред\n\nрдпрд╛ рдЖрдк рдХрд░ рд╕рдХрддреЗ рд╣реИрдВ:\nтАв рд░реЗрд╕реНрддрд░рд╛рдВ рдмреНрд░рд╛рдЙрдЬрд╝ рдХрд░реЗрдВ\nтАв рд╣рдорд╛рд░рд╛ рдореЗрдиреВ рджреЗрдЦреЗрдВ\nтАв рд╣рдорд╛рд░реА рд╕реЗрд╡рд╛рдУрдВ рдХреЗ рдмрд╛рд░реЗ рдореЗрдВ рдЬрд╛рдиреЗрдВ"
      mr: "рдирдорд╕реНрдХрд╛рд░! ЁЯСЛ Mangwale рдордзреНрдпреЗ рдЖрдкрд▓реЗ рд╕реНрд╡рд╛рдЧрдд!\n\nрдореА рдЬреЗрд╡рдг рдСрд░реНрдбрд░ рдХрд░рдгреНрдпрд╛рд╕рд╛рдареА рддреБрдордЪрд╛ AI рд╕рд╣рд╛рдпреНрдпрдХ рдЖрд╣реЗ.\n\nрд╕реБрд░реВ рдХрд░рдгреНрдпрд╛рд╕рд╛рдареА, рдХреГрдкрдпрд╛ рдиреЛрдВрджрдгреАрд╕рд╛рдареА рддреБрдордЪрд╛ рдлреЛрди рдирдВрдмрд░ рд╢реЗрдЕрд░ рдХрд░рд╛.\n\nрдХрд┐рдВрд╡рд╛ рддреБрдореНрд╣реА:\nтАв рд░реЗрд╕реНрдЯреЙрд░рдВрдЯреНрд╕ рдмреНрд░рд╛рдЙрдЭ рдХрд░рд╛\nтАв рдЖрдордЪрд╛ рдореЗрдиреВ рдкрд╣рд╛\nтАв рдЖрдордЪреНрдпрд╛ рд╕реЗрд╡рд╛рдВрдмрджреНрджрд▓ рдЬрд╛рдгреВрди рдШреНрдпрд╛"
    next: wait_for_new_user_input

  - id: wait_for_new_user_input
    type: input
    input_type: text
    next: transfer_to_registration

  - id: transfer_to_registration
    type: flow_transfer
    target_flow: customer_registration

# Error handling
error_handler:
  - id: error_fallback
    type: message
    message:
      en: "I encountered an issue detecting your account. Let me connect you with support."
      hi: "рдЖрдкрдХрд╛ рдЦрд╛рддрд╛ рдкрд╣рдЪрд╛рдирдиреЗ рдореЗрдВ рд╕рдорд╕реНрдпрд╛ рд╣реБрдИред рдореБрдЭреЗ рдЖрдкрдХреЛ рд╕рд╣рд╛рдпрддрд╛ рд╕реЗ рдЬреЛрдбрд╝рдиреЗ рджреЗрдВред"
      mr: "рддреБрдордЪреЗ рдЦрд╛рддреЗ рдУрд│рдЦрдгреНрдпрд╛рдд рд╕рдорд╕реНрдпрд╛ рдЖрд▓реА. рдорд▓рд╛ рддреБрдореНрд╣рд╛рд▓рд╛ рд╕рдорд░реНрдердирд╛рд╢реА рдЬреЛрдбреВ рджреНрдпрд╛."
