#!/usr/bin/env python3
"""
Generate comprehensive NLU training data v5 for MangwaleAI IndicBERT.

Strategy:
- Consolidate 63 raw intents into ~35 canonical intents (merge synonyms)
- 120+ examples per intent (mix of EN, HI, Marathi, code-mixed)
- Include typos, abbreviations, voice-to-text artifacts
- Balanced dataset for better generalization

The flow engine maps multiple trigger_intents to a single flow,
so we only need one canonical label per group.
"""

import json
import random
import os

# Seed for reproducibility
random.seed(42)

# ============================================================
# CANONICAL INTENT DEFINITIONS
# Each intent has: templates (parameterized), slot_fills, and static examples
# ============================================================

TRAINING_DATA = {
    # ============================================================
    # FOOD ORDERING FLOW
    # ============================================================
    "order_food": {
        "description": "User wants to order food (general intent)",
        "aliases": ["hungry", "search_food"],
        "examples": [
            # English
            "I want to order food",
            "order food",
            "I'm hungry",
            "I want to eat something",
            "get me some food",
            "order karo",
            "food order karna hai",
            "mujhe khana chahiye",
            "I need food",
            "can I order food here?",
            "food delivery please",
            "I want food delivered",
            "order something to eat",
            "get food delivered",
            "khana mangwana hai",
            "food mangwa do",
            "bhook lagi hai",
            "bohot bhook lagi hai mujhe",
            "kuch khane ko order karo",
            "mujhe kuch khana hai",
            "food order place karna hai",
            "I'm starving, order food",
            "need food ASAP",
            "hungry, want food now",
            "can you order food for me?",
            "place a food order",
            "I want to order lunch",
            "dinner order karna hai",
            "breakfast order karo",
            "late night food chahiye",
            "order dinner for me",
            "I want biryani",
            "mujhe pizza chahiye",
            "paneer butter masala order karo",
            "send me a burger",
            "I need some pasta",
            "vada pav mangwa do",
            "momos order karo",
            "get me some dosa",
            "I want chicken tikka",
            "order noodles",
            "mujhe thali chahiye",
            "I want to order dal rice",
            "sandwich order karna hai",
            "I want a combo meal",
            "get me fried rice",
            "I need idli sambar",
            "order chole bhature",
            "pav bhaji chahiye mujhe",
            "I want some ice cream",
            "milkshake order karo",
            "cold coffee chahiye",
            "I need a drink",
            "juice order karna hai",
            "food lao yaar",
            "pet bhar khana do",
            "aaj kya khaye",
            "khana order karo bhai",
            "zomato jaisa order karo",
            "swiggy se mangwa do",
            "ghar pe food delivery chahiye",
            "office mein lunch mangwana hai",
            "party ke liye food order karo",
            "I want Chinese food",
            "South Indian food chahiye",
            "Mughlai khana order karo",
            "Italian food chahiye",
            "something spicy",
            "kuch meetha chahiye",
            "non-veg food order karna hai",
            "pure veg khana chahiye",
            "Jain food available hai?",
            "I want food without onion garlic",
            "diet food chahiye",
            "healthy food order karo",
            "quick food chahiye jaldi se",
            "fast delivery food",
            "koi accha restaurant se khana",
            "best rated food order karo",
            "cheap food delivery",
            "budget mein food chahiye",
            "i wnat to eat somthing",
            "ordeer food plz",
            "fod delivery",
            "i want to oder food",
            "i need fod",
            "food ordr karna hai",
            "khana magwa do",
            "bhuk lagi hai",
            "muje kuch khana hai",
            "food order krna hai",
            "mla khana pahije",
            "jevayala kahi order kara",
            "khayala kahi magva",
            "mala jeva pahije",
            "bhuk lagali",
            "kahi khayala magv",
            "jevnachi order dya",
            "ek pizza dya",
            "biryani pathav",
            "paneer order kara",
            "chicken fry magva",
            "mala misal pahije",
            "vada pav pathva",
            "sabudana vada magva",
            "poha dya ek",
            "thalipeeth order kara",
            "मला जेवायला काही मागव",
            "मला भूक लागली आहे",
            "जेवणाची ऑर्डर द्या",
            "पिझ्झा ऑर्डर करा",
            "बिर्याणी पाठवा",
            "मला खायला काही हवं",
            "मुझे खाना चाहिए",
            "भूख लगी है",
            "ऑर्डर करो खाना",
            "फूड डिलिवरी चाहिए",
        ],
    },

    "browse_menu": {
        "description": "User wants to see menu/options from a restaurant",
        "aliases": [],
        "examples": [
            "show me the menu",
            "menu dikhao",
            "what's on the menu?",
            "menu card please",
            "show menu",
            "let me see the menu",
            "what do you have?",
            "kya kya milta hai?",
            "what items available?",
            "restaurant ka menu batao",
            "full menu dikhao",
            "kya options hain?",
            "menu list",
            "show all items",
            "aaj ka menu kya hai",
            "today's special kya hai",
            "what's available today?",
            "list all dishes",
            "available items batao",
            "food menu",
            "show food options",
            "kya kya order kar sakte hain",
            "menu mein kya kya hai",
            "what cuisines available?",
            "vegetarian menu dikhao",
            "non veg menu",
            "dessert menu",
            "drinks menu dikhao",
            "starter menu",
            "main course options",
            "thali menu dikhao",
            "combo meals dikhao",
            "snacks menu",
            "breakfast menu",
            "lunch menu dikhao",
            "dinner options kya hain",
            "menu batao please",
            "kya serve karte ho",
            "dish list dikha do",
            "what can I order?",
            "menu me kya hai",
            "sab items dikha do",
            "restaurant ki list",
            "pura menu chahiye",
            "complete menu dikha do",
            "I want to see what's available",
            "show me options",
            "what all can I get?",
            "categories dikhao",
            "food categories",
            "menu kartik",
            "show me your food list",
            "kya items hai aapke paas",
            "menuu dikhao",
            "menu card dikha do",
            "aapka menu kya hai",
            "dish options batao",
            "available food items",
            "menu dekhna hai",
            "I want to see the menu first",
            "pehle menu dikhao phir order karunga",
            "menu दाखवा",
            "काय काय मिळतं?",
            "menu कार्ड दाखवा",
            "आज काय special आहे?",
            "सगळे items दाखवा",
            "restaurant चा menu दाखवा",
            "काय options आहेत?",
            "menu list दाखवा",
            "पूर्ण menu दाखवा",
            "jeva menu dakhva",
            "kay kay milta",
            "aajcha special kay",
            "sagla menu dakhva",
            "options dakhva",
            "kay order karu shakto",
            "items chi list dya",
            "khayala kay milta",
            "restaurant madhla menu",
            "dish list dya",
            "veg menu dakhva",
            "non veg menu dakhva",
            "dessert options kay ahet",
            "combo meals dakhva",
            "snacks menu dakhva",
            "menyu dikhao",
            "show menue",
            "manu dikhao",
            "menu dikahdo",
            "what is on menue",
            "manu card",
            "shw menu",
            "items list pls",
            "kya kya milta h",
            "menu m kya h",
            "sab item dikha",
            "options btao",
            "what u have",
            "menu plz",
            "menu plss dikha do",
            "bhai menu bhej",
            "ek baar menu dikha do yaar",
        ],
    },

    "browse_stores": {
        "description": "User wants to see available restaurants/stores",
        "aliases": ["browse_category"],
        "examples": [
            "show me nearby restaurants",
            "restaurants near me",
            "which stores are available?",
            "show me shops",
            "nearby food places",
            "kaunse restaurants hain",
            "paas mein kya kya hai",
            "which restaurants deliver here?",
            "show all restaurants",
            "available stores",
            "restaurant list dikhao",
            "stores near me",
            "list of restaurants",
            "show me food joints",
            "nearby dhabas",
            "cafes near me",
            "bakery shops",
            "sweet shops near me",
            "fast food places",
            "Chinese restaurants near me",
            "pizza places near me",
            "biryani shops near me",
            "best restaurants in my area",
            "top rated restaurants",
            "popular restaurants dikhao",
            "new restaurants",
            "recently opened restaurants",
            "restaurants open now",
            "which shops are open?",
            "24 hour restaurants",
            "late night food places",
            "pure veg restaurants",
            "non veg restaurants near me",
            "family restaurants",
            "budget restaurants",
            "premium restaurants",
            "show me all options",
            "food delivery restaurants",
            "konse restaurants hai",
            "shops ki list dikhao",
            "kahan se order karun",
            "best place for pizza",
            "best biryani shop",
            "acha restaurant batao",
            "famous restaurants",
            "trending restaurants",
            "highest rated shops",
            "restaurant batao koi acha sa",
            "stores list do",
            "shops batao",
            "restaurant dikhao nearby",
            "paas ke restaurant",
            "mere area mein kya hai",
            "delivery available restaurants",
            "kaunse shops deliver karte hain",
            "open restaurants list",
            "konse store se order karu",
            "restaurants batao na",
            "which stores deliver to me",
            "show nearby stores",
            "list restaurants",
            "konse restaurants open hai",
            "restaurnt near me",
            "nearbye restaurants",
            "restarants dikhao",
            "shops list pls",
            "stroes near me",
            "restaurant lst dikhao",
            "जवळचे restaurants दाखवा",
            "कोणते restaurants आहेत",
            "stores ची list दाखवा",
            "जवळचे दुकान दाखवा",
            "restaurant list dya",
            "javlache shops dakhva",
            "konti restaurants ahet",
            "open restaurants dakhva",
            "best restaurants dakhva",
            "delivery konte stores kartat",
        ],
    },

    "ask_recommendation": {
        "description": "User asks for food/restaurant recommendations",
        "aliases": ["ask_famous", "ask_fastest_delivery"],
        "examples": [
            "what do you recommend?",
            "suggest something",
            "kya suggest karoge?",
            "what's popular?",
            "best seller kya hai?",
            "trending items",
            "what should I order?",
            "kya order karun?",
            "recommend me something good",
            "best food here",
            "most ordered item",
            "what's famous?",
            "famous items",
            "popular dishes batao",
            "highest rated dish",
            "kya accha hai yahan?",
            "best dish batao",
            "top picks",
            "suggest something spicy",
            "veg mein kya accha hai?",
            "non veg mein best kya hai?",
            "dessert recommend karo",
            "best pizza",
            "best biryani kahan milegi?",
            "sabse famous kya hai?",
            "kya try karun?",
            "new items suggest karo",
            "chef's special kya hai?",
            "must try items",
            "suggest something healthy",
            "diet food recommend karo",
            "light snack suggest karo",
            "party ke liye kya order karun?",
            "date ke liye suggest karo",
            "family dinner ke liye best?",
            "sabse fast delivery kiska hai?",
            "fastest delivery kahan se milegi?",
            "jaldi food chahiye suggest karo",
            "quick delivery restaurant batao",
            "30 min mein kya aa jayega?",
            "quickest delivery option",
            "suggest karo kya khau",
            "accha sa kuch batao",
            "koi new try karu?",
            "best combo meal",
            "value for money kya hai?",
            "sasta aur accha",
            "kya milega 100 rupees mein?",
            "under 200 mein kya milega?",
            "budget friendly suggest karo",
            "premium suggest karo",
            "special occasion ke liye",
            "bestseller kya hai",
            "most popular item batao",
            "customer favorites dikhao",
            "top 5 items",
            "suggest karo na kuch accha",
            "kuch suggest kr do",
            "recommend smthing",
            "what is best here",
            "sugst something",
            "kya famous h",
            "popular items btao",
            "best food btao",
            "काय suggest कराल?",
            "best काय आहे?",
            "popular items दाखवा",
            "famous काय आहे इथे?",
            "kay khau suggest kara",
            "best item dakhva",
            "popular dishes dakhva",
            "famous items kay ahet",
            "suggest kara kahi",
            "trending dishes",
            "most liked items",
            "customer favorite kya hai",
        ],
    },

    "ask_price": {
        "description": "User asks about price of item or delivery",
        "aliases": ["price_inquiry"],
        "examples": [
            "how much does it cost?",
            "what's the price?",
            "kitna hai?",
            "price batao",
            "kya rate hai?",
            "total kitna hoga?",
            "delivery charges kya hai?",
            "is there delivery fee?",
            "kitna paisa lagega?",
            "pizza ka price kya hai?",
            "biryani kitne ki hai?",
            "rate dikhao",
            "price list",
            "cost kya hai?",
            "kitne ka hai ye?",
            "yeh kitne ka hai",
            "total bill kya hoga?",
            "estimated cost batao",
            "what will be the total?",
            "delivery charge kitna hai?",
            "free delivery hai?",
            "extra charges hain?",
            "GST included hai?",
            "tax kitna lagega?",
            "minimum order kya hai?",
            "minimum order amount?",
            "how much for delivery?",
            "price check karo",
            "kitne ka padega?",
            "cost estimate do",
            "kya price hai iska?",
            "rate kya hai?",
            "charges batao",
            "total amount bata do",
            "final price kya hogi?",
            "discount ke baad kitna hoga?",
            "after discount price?",
            "MRP kya hai?",
            "original price kya hai?",
            "offer price kya hai?",
            "how much will it cost with delivery?",
            "total with delivery charges?",
            "packaging charges hain?",
            "hidden charges hain?",
            "complete bill batao",
            "kitne ka hai sab mila ke?",
            "price dekh lo",
            "yeh mehnga hai",
            "is it expensive?",
            "affordable hai?",
            "sasta option hai?",
            "cheaper option?",
            "kitne rupees?",
            "howmuch",
            "kitna h",
            "price btao",
            "charges kya h",
            "total kitna hga",
            "delivery free h kya",
            "किती आहे?",
            "price सांगा",
            "delivery charges किती?",
            "total किती होईल?",
            "kiti ahe",
            "price sanga",
            "delivery charges kiti",
            "total kiti hoil",
            "kiti rupaye",
            "rate kay ahe",
        ],
    },

    "check_offers": {
        "description": "User asks about offers, discounts, or coupons",
        "aliases": ["apply_coupon"],
        "examples": [
            "any offers?",
            "koi offer hai?",
            "discount available?",
            "show me offers",
            "current offers",
            "today's offers",
            "koi coupon hai?",
            "discount code hai?",
            "promo code",
            "apply coupon",
            "I have a coupon code",
            "offer dikhao",
            "koi deal chal raha hai?",
            "aaj ka offer kya hai?",
            "best deals batao",
            "cashback milega?",
            "free delivery offer hai?",
            "buy 1 get 1 hai?",
            "BOGO offer?",
            "festival offer",
            "special discount hai?",
            "loyalty discount",
            "first order discount?",
            "new user offer?",
            "referral discount",
            "coupon apply karo",
            "mera coupon laga do",
            "coupon code hai: FLAT50",
            "use coupon SAVE20",
            "coupon lagao",
            "offer lagao",
            "discount de do",
            "kuch offer lagao",
            "sasta karo",
            "discount milega kya?",
            "offers kya chal rahe hain?",
            "sale hai kya?",
            "happy hours?",
            "lunch offer",
            "dinner deal",
            "combo offer",
            "family pack offer",
            "bulk discount?",
            "wholesale rate milega?",
            "membership discount?",
            "wallet offer hai?",
            "paytm offer?",
            "UPI discount?",
            "any cashback offers?",
            "koi promo code hai?",
            "coupon code btao",
            "offr h kya",
            "discount h koi",
            "ofr dikhao",
            "deals btao",
            "कोई offer आहे का?",
            "discount आहे?",
            "coupon apply करा",
            "offer दाखवा",
            "kahi offer ahe ka",
            "discount ahe ka",
            "coupon lava",
            "aajche offers kay ahet",
            "deals dakhva",
        ],
    },

    "add_to_cart": {
        "description": "User wants to add a specific item to cart",
        "aliases": [],
        "examples": [
            "add to cart",
            "add this",
            "cart mein daal do",
            "add it",
            "yes add this one",
            "add pizza to cart",
            "cart mein add karo",
            "add 2 of these",
            "add one more",
            "mujhe ye chahiye",
            "ye daal do",
            "add karo",
            "cart mein daalo",
            "I'll take this",
            "I want this one",
            "select this",
            "add this item",
            "add the first one",
            "add option 1",
            "add option 2",
            "add option 3",
            "pehla wala add karo",
            "doosra wala daal do",
            "ye wala chahiye",
            "add biryani to my cart",
            "pizza add karo",
            "burger add karo cart mein",
            "add 3 plates momos",
            "2 vada pav add karo",
            "1 paneer tikka add",
            "add it to my order",
            "I want to add more items",
            "ek aur add karo",
            "aur kuch add karna hai",
            "ye bhi add karo",
            "this also add karo",
            "put this in cart",
            "put in my cart",
            "add this to order",
            "select karo",
            "haan ye wala",
            "haan add karo",
            "okay add this",
            "done, add it",
            "cart me dal do",
            "add kr do",
            "ye add kro",
            "cart me add kr do",
            "haan ye daal do",
            "add krdo",
            "cart m daalo",
            "cart madhye ghala",
            "हे add करा",
            "cart मध्ये घाला",
            "हे हवं",
            "cart madhe ghal",
            "he add kara",
            "he pahije",
            "add kara cart madhe",
            "he ghal",
            "cart la add kara",
            "pehla option ghal",
            "ek pizza add kara",
            "ha items add kara",
            "add 2 plates",
            "3 pieces add karo",
            "ek aur piece add karo",
            "sabhi add karo",
        ],
    },

    "view_cart": {
        "description": "User wants to see what's in their cart",
        "aliases": [],
        "examples": [
            "show my cart",
            "view cart",
            "what's in my cart?",
            "cart dikhao",
            "mere cart mein kya hai?",
            "show cart",
            "my cart",
            "open cart",
            "cart items",
            "cart check karo",
            "cart dekho",
            "mera cart dikha do",
            "cart mein kya hai",
            "let me see my cart",
            "show me what I've added",
            "order summary dikhao",
            "cart summary",
            "items in cart",
            "how many items in cart?",
            "cart total batao",
            "cart ka total kya hai?",
            "mera order dikhao",
            "selected items dikhao",
            "added items list",
            "cart value kitni hai?",
            "cart update dikhao",
            "current cart status",
            "kya add kiya hai maine?",
            "jo add kiya hai wo dikhao",
            "show selected items",
            "pending order dikhao",
            "my selections",
            "cart list",
            "order list dikhao",
            "sab items dikha do jo add kiye",
            "cart m kya h",
            "cart dikhao bhai",
            "mera cart btao",
            "items kya add kiye h",
            "show cart plz",
            "cart dkaho",
            "cart me kya kya h",
            "cart दाखवा",
            "माझ्या cart मध्ये काय आहे?",
            "cart check करा",
            "cart dakhva",
            "mazya cart madhe kay ahe",
            "cart check kara",
            "kiti items cart madhe ahet",
            "cart total kiti ahe",
            "cart list dya",
        ],
    },

    "update_quantity": {
        "description": "User wants to change quantity of an item in cart",
        "aliases": [],
        "examples": [
            "change quantity",
            "update quantity",
            "increase quantity",
            "decrease quantity",
            "make it 2",
            "I want 3 instead",
            "change to 5",
            "quantity badhao",
            "quantity kam karo",
            "ek aur add karo",
            "one more",
            "double it",
            "make it double",
            "reduce to 1",
            "quantity change karo",
            "2 plates karo",
            "3 pieces chahiye",
            "5 plates karo",
            "quantity update karo",
            "increase to 4",
            "decrease to 2",
            "add one more piece",
            "remove one piece",
            "ek kam karo",
            "ek aur daal do",
            "do aur chahiye",
            "teen karo",
            "char karo",
            "paanch chahiye",
            "quantity set karo 3",
            "half portion chahiye",
            "full portion karo",
            "large size karo",
            "medium size mein change karo",
            "small size chahiye",
            "regular to large",
            "make it large",
            "extra large chahiye",
            "portion badhao",
            "quantity kam kr do",
            "ek aur bhi add kr do",
            "2 or kro",
            "kitni chahiye change karo",
            "ek extra daal do",
            "quantity वाढवा",
            "कमी करा",
            "आणखी एक",
            "quantity vadhva",
            "kami kara",
            "anakhi ek",
            "don kara",
            "teen kara",
        ],
    },

    "remove_from_cart": {
        "description": "User wants to remove an item from cart",
        "aliases": [],
        "examples": [
            "remove from cart",
            "remove this item",
            "delete from cart",
            "cart se hatao",
            "remove karo",
            "nikal do",
            "ye nahi chahiye",
            "I don't want this",
            "remove it",
            "take this out",
            "cart se nikal do",
            "remove pizza from cart",
            "delete this item",
            "hatao ye",
            "ye nahi chahiye mujhe",
            "cancel this item",
            "remove the biryani",
            "take out the burger",
            "ye item hata do",
            "remove last item",
            "pehla item nikal do",
            "remove first item",
            "ye order se hata do",
            "don't want this anymore",
            "changed my mind about this",
            "remove ye wala",
            "cart se ye hata do",
            "I want to remove something",
            "ek item remove karna hai",
            "cart update karo, ye hatao",
            "remove kr do",
            "hata do ye",
            "nhi chahiye ab",
            "cancel kro ye item",
            "nikal do cart se",
            "cart मधून काढा",
            "हे नको",
            "remove करा",
            "cart madhun kadha",
            "he nako",
            "remove kara he",
            "hatva he item",
            "cart madhun hatva",
        ],
    },

    "clear_cart": {
        "description": "User wants to clear entire cart",
        "aliases": [],
        "examples": [
            "clear cart",
            "empty cart",
            "remove all items",
            "sab hata do",
            "cart khali karo",
            "clear everything",
            "start over",
            "fresh start",
            "delete all items",
            "remove everything from cart",
            "cart clear karo",
            "sab delete karo",
            "poora cart khali karo",
            "I don't want anything",
            "cancel everything",
            "sab cancel karo",
            "empty my cart",
            "cart reset karo",
            "new order start karo",
            "phir se shuru karo",
            "remove all",
            "sab hatao",
            "kuch nahi chahiye ab",
            "naya order karna hai",
            "cart clear kr do",
            "sab hta do",
            "kuch nhi chahiye",
            "cart clear kra do",
            "sab cancel",
            "pura cart hatao",
            "cart रिकामं करा",
            "सगळं काढा",
            "cart clear करा",
            "cart rikama kara",
            "sagla kadha",
            "cart clear kara",
            "navi order suru kara",
            "sab items delete karo",
            "poora order cancel",
        ],
    },

    "customize_order": {
        "description": "User wants to customize food (extra cheese, less spicy, etc.)",
        "aliases": [],
        "examples": [
            "extra cheese please",
            "less spicy",
            "make it spicy",
            "no onion",
            "without garlic",
            "extra sauce",
            "less salt",
            "add extra toppings",
            "remove onion",
            "extra masala",
            "medium spicy",
            "very spicy chahiye",
            "mild flavor",
            "extra butter",
            "no mayo",
            "add cheese",
            "double cheese",
            "extra crunchy",
            "well done",
            "half fry",
            "full fry",
            "gravy extra chahiye",
            "dry banana do",
            "boneless chahiye",
            "with bone",
            "extra raita add karo",
            "no pickle",
            "extra chutney",
            "sugar free",
            "diet coke chahiye",
            "jain preparation mein banana",
            "without onion garlic",
            "extra green chili",
            "less oil",
            "no MSG",
            "organic chahiye",
            "gluten free option hai?",
            "extra paneer daal do",
            "double meat",
            "toppings add karo",
            "customize karna hai",
            "special instructions: no peanuts",
            "allergic to nuts, please note",
            "no dairy please",
            "vegan option mein banana",
            "extra spicy kr do",
            "less mirchi",
            "without pyaaz",
            "extra butter dal do",
            "cheese extra kro",
            "तिखट कमी करा",
            "extra cheese टाका",
            "कांदा नको",
            "tikhat kami kara",
            "extra cheese taka",
            "kanda nako",
            "extra masala ghala",
            "kam tikhat",
            "bohot jyada spicy",
        ],
    },

    "checkout": {
        "description": "User wants to proceed to checkout/payment",
        "aliases": ["confirm_checkout"],
        "examples": [
            "checkout",
            "proceed to checkout",
            "place order",
            "order place karo",
            "checkout karo",
            "proceed to payment",
            "pay now",
            "I want to pay",
            "complete order",
            "finalize order",
            "confirm order",
            "order confirm karo",
            "book order",
            "submit order",
            "payment karo",
            "place my order",
            "order karo",
            "final order",
            "done, checkout",
            "okay proceed",
            "let's order",
            "order de do",
            "place it",
            "confirm and pay",
            "ready to order",
            "order ready hai",
            "haan order karo",
            "proceed",
            "go ahead and order",
            "order place kr do",
            "payment kr do",
            "book kr do",
            "order kr do bhai",
            "haan confirm karo",
            "bas order de do",
            "done ordering",
            "I'm done, place order",
            "sab add ho gaya, order karo",
            "cart ready hai, order karo",
            "chalo order karte hain",
            "let's do it",
            "confirm it",
            "order confirm",
            "haan chalega",
            "final order de do",
            "order place please",
            "payment page pe le jao",
            "razorpay se pay karna hai",
            "online payment",
            "cash on delivery",
            "COD chahiye",
            "UPI se pay karunga",
            "checkout kr do",
            "ordr place kro",
            "payment kro",
            "ordr karo",
            "confirm krdo",
            "order दया",
            "checkout करा",
            "payment करा",
            "order confirm करा",
            "order dya",
            "checkout kara",
            "payment kara",
            "order confirm kara",
            "haan order dya",
            "chala order karuyat",
        ],
    },

    "repeat_order": {
        "description": "User wants to repeat a previous order",
        "aliases": [],
        "examples": [
            "repeat my last order",
            "same order again",
            "repeat order",
            "last order phir se",
            "wahi order karo",
            "same as before",
            "order again",
            "reorder",
            "previous order repeat karo",
            "last time ka order",
            "same order",
            "jo pichli baar order kiya tha",
            "fir se wahi",
            "repeat karo",
            "wahi food order karo",
            "last order same",
            "previous order dedo",
            "jo kal order kiya tha wahi",
            "ek baar phir wahi",
            "same items order karo",
            "repeat last",
            "duplicate order",
            "same food again",
            "reorder the same",
            "order wahi jo last time tha",
            "pichla order repeat",
            "usual order karo",
            "my regular order",
            "regular order de do",
            "mera usual",
            "the usual please",
            "always wala order",
            "roz wala order",
            "daily order",
            "what I usually get",
            "same thing",
            "repeat kr do",
            "whi order kr do",
            "same ordr",
            "last wala repeat",
            "phir se whi",
            "मागची order परत द्या",
            "तेच order करा",
            "same order करा",
            "magchi order parat dya",
            "tech order kara",
            "same order kara",
            "repeat kara",
            "parat tech",
        ],
    },

    "cancel_order": {
        "description": "User wants to cancel a placed order",
        "aliases": [],
        "examples": [
            "cancel my order",
            "cancel order",
            "I want to cancel",
            "order cancel karo",
            "cancel karo",
            "mujhe order cancel karna hai",
            "cancel please",
            "I don't want this order",
            "order cancel",
            "cancel it",
            "please cancel my order",
            "cancel the order I just placed",
            "last order cancel karo",
            "I changed my mind",
            "don't deliver",
            "delivery mat karo",
            "order band karo",
            "stop my order",
            "I want to cancel everything",
            "cancel all orders",
            "abhi cancel karo",
            "jaldi cancel karo",
            "turant cancel",
            "cancel right now",
            "order cancel kr do",
            "cancel krna hai",
            "mera order cancel kro",
            "order nhi chahiye ab",
            "order band kro",
            "delivery cancel",
            "order cancel करा",
            "मला order cancel करायचं आहे",
            "cancel करा",
            "order cancel kara",
            "mala order cancel karaycha ahe",
            "cancel kara",
            "order nako",
            "delivery nako",
        ],
    },

    "bulk_order": {
        "description": "User wants to place a large/bulk order",
        "aliases": ["multi_store_order", "schedule_order"],
        "examples": [
            "I want to place a bulk order",
            "bulk order karna hai",
            "large order for party",
            "party order",
            "50 plates chahiye",
            "order for 20 people",
            "catering order",
            "office lunch for 30",
            "bulk food order",
            "corporate order",
            "event ke liye food",
            "wedding food order",
            "birthday party order",
            "bulk discount milega?",
            "zyada quantity mein order",
            "100 samosas chahiye",
            "party pack order",
            "large quantity order",
            "30 log ka order",
            "team lunch order",
            "meeting ke liye food order",
            "conference food",
            "get-together ke liye",
            "multiple stores se order karna hai",
            "do restaurants se order karna hai",
            "alag alag shops se mangwana hai",
            "ek restaurant se pizza aur doosre se biryani",
            "schedule order for tomorrow",
            "advance order karna hai",
            "kal ke liye order karo",
            "pre-order food",
            "order schedule karo",
            "time set karo delivery ka",
            "2 baje ke liye order karo",
            "lunch time delivery",
            "dinner 8 baje",
            "advance mein book karo",
            "kal subah ke liye",
            "weekend ke liye order",
            "Sunday brunch order",
            "bulk order for office",
            "10 biryani plates chahiye",
            "multiple items from different shops",
            "2-3 shops se order",
            "advance booking for party",
            "schedule delivery for evening",
            "bulk ordr",
            "party ke liye food",
            "bahut saara food chahiye",
            "बल्क order करायचं आहे",
            "party साठी food",
            "advance order करा",
            "bulk order karaycha ahe",
            "party sathi food",
            "advance order kara",
            "kal sathi food book kara",
            "office lunch order kara",
        ],
    },

    # ============================================================
    # SEARCH/PRODUCT FLOW
    # ============================================================
    "search_product": {
        "description": "User searching for a specific product (e-commerce)",
        "aliases": [],
        "examples": [
            "search for mobile cover",
            "I'm looking for shoes",
            "show me headphones",
            "find me a laptop",
            "search mobile phone",
            "I want to buy a watch",
            "show me t-shirts",
            "search for bags",
            "I need a charger",
            "looking for earphones",
            "bluetooth speaker chahiye",
            "power bank dikhao",
            "phone cover",
            "search karo mobile case",
            "laptop bag dikhao",
            "smartwatch options",
            "tablet chahiye",
            "camera dikhao",
            "gym equipment search karo",
            "home decor items",
            "furniture dikhao",
            "kitchen appliances",
            "electronics search",
            "fashion items dikhao",
            "beauty products",
            "skin care products",
            "hair products dikhao",
            "books search karo",
            "toys for kids",
            "baby products",
            "pet food",
            "cleaning supplies",
            "stationery items",
            "office supplies",
            "sports equipment",
            "musical instruments",
            "art supplies dikhao",
            "gardening tools",
            "car accessories",
            "bike accessories search",
            "I want to buy something",
            "show me products",
            "product search",
            "shopping karna hai",
            "search for gifts",
            "gift options dikhao",
            "valentine gift",
            "birthday gift search",
            "anniversary gift",
            "search krna hai",
            "product dikha do",
            "items search kro",
            "headphone dikhao",
            "shose dikhao",
            "mobile covr",
            "I want to by a watch",
            "शूज दाखवा",
            "mobile cover दाखवा",
            "products शोधा",
            "shoes dakhva",
            "mobile cover dakhva",
            "products shodhaa",
            "laptop dakhva",
            "headphones dakhva",
            "watch pahije",
        ],
    },

    # ============================================================
    # PARCEL DELIVERY FLOW
    # ============================================================
    "parcel_booking": {
        "description": "User wants to send/book a parcel/courier",
        "aliases": ["book_parcel", "send_parcel"],
        "examples": [
            "I want to send a parcel",
            "book a parcel",
            "parcel booking",
            "send package",
            "courier chahiye",
            "parcel bhejna hai",
            "send a courier",
            "parcel book karo",
            "I need to send something",
            "delivery karna hai",
            "pick up and deliver",
            "pickup and drop",
            "mujhe parcel bhejna hai",
            "courier booking karna hai",
            "send from here to there",
            "package delivery",
            "book courier",
            "parcel service",
            "document deliver karna hai",
            "medicine deliver karna hai",
            "food parcel",
            "gift deliver karo",
            "flowers deliver karo",
            "cake deliver karo",
            "same day delivery chahiye",
            "urgent parcel",
            "express delivery",
            "parcel track bhi karna hai",
            "parcel ka rate kya hai?",
            "parcel charges?",
            "COD parcel",
            "prepaid parcel",
            "pickup from home",
            "office se pickup",
            "parcel bhejna h",
            "courier krna hai",
            "parcel book kro",
            "pickup krwana h",
            "send krna hai package",
            "parcel pathvaycha ahe",
            "courier करायचा आहे",
            "parcel booking करा",
            "package पाठवा",
            "parcel pathvaycha ahe",
            "courier karaycha ahe",
            "parcel booking kara",
            "package pathva",
            "document pathva",
            "urgent parcel pathva",
            "pickup and delivery kara",
            "मुझे पार्सल भेजना है",
            "कूरियर बुक करो",
            "पिकअप चाहिए",
            "पार्सल बुकिंग",
            "mujhe parcel bhejhna hai",
            "couri book karo",
            "pickup chahiye ghar se",
        ],
    },

    # ============================================================
    # ORDER TRACKING FLOW
    # ============================================================
    "track_order": {
        "description": "User wants to track their order status",
        "aliases": ["order_status"],
        "examples": [
            "track my order",
            "where is my order?",
            "order status",
            "delivery kab hogi?",
            "mera order kahan hai?",
            "track order",
            "order tracking",
            "when will my order arrive?",
            "delivery status",
            "ETA kya hai?",
            "kitna time lagega?",
            "order kab aayega?",
            "food kab milega?",
            "delivery time kya hai?",
            "rider kahan hai?",
            "delivery boy kahan hai?",
            "order status check karo",
            "is my order on the way?",
            "has my order been dispatched?",
            "order out for delivery?",
            "mera order aa raha hai?",
            "delivery ka update do",
            "order ka status batao",
            "abhi kahan hai mera order?",
            "kitni door hai delivery?",
            "estimated time of arrival",
            "order confirm ho gaya?",
            "order accepted?",
            "restaurant ne accept kiya?",
            "cooking start hui?",
            "food ready hai?",
            "order picked up?",
            "rider assigned?",
            "delivery started?",
            "almost yahan hai?",
            "kitne min mein aayega?",
            "last mile delivery status",
            "order update chahiye",
            "notification nahi aayi",
            "order status btao",
            "kab aayega mera ordr",
            "delivery kab hgi",
            "order track kro",
            "mera order khn h",
            "कधी येईल order?",
            "order status सांगा",
            "delivery कधी होईल?",
            "order कुठे आहे?",
            "kadhi yeil order",
            "order status sanga",
            "delivery kadhi hoil",
            "order kuthe ahe",
            "rider kuthe ahe",
            "food kadhi milel",
        ],
    },

    # ============================================================
    # ADDRESS MANAGEMENT FLOW
    # ============================================================
    "manage_address": {
        "description": "User shares location, adds/changes address",
        "aliases": [],
        "examples": [
            "change my address",
            "update address",
            "add new address",
            "my address is wrong",
            "set delivery address",
            "address change karo",
            "naya address add karo",
            "delivery address set karo",
            "location share karta hun",
            "address update karna hai",
            "save this address",
            "delete address",
            "remove old address",
            "default address change karo",
            "office address add karo",
            "home address set karo",
            "use different address",
            "deliver to a different location",
            "address galat hai",
            "wrong address fix karo",
            "GPS location",
            "share my location",
            "pin location",
            "map se location do",
            "📍 sharing location",
            "here is my location",
            "deliver here",
            "yahan deliver karo",
            "is address pe bhejo",
            "location bhej raha hun",
            "address save karo",
            "address list dikhao",
            "saved addresses dikhao",
            "my addresses",
            "address book",
            "landmark: near petrol pump",
            "flat no 301, building ABC",
            "address: MG Road, Nashik",
            "deliver to home",
            "deliver to office",
            "address change krna h",
            "naya address add krdo",
            "location share kr rha",
            "address update kr do",
            "address save kro",
            "address बदला",
            "नवीन address add करा",
            "location share करतो",
            "delivery address set करा",
            "address badla",
            "navin address add kara",
            "location share karto",
            "delivery address set kara",
            "address save kara",
            "address update kara",
            "19.9876, 73.7890",
            "coordinates: 19.97, 73.78",
            "https://maps.app.goo.gl/abc123",
            "Google Maps link",
        ],
    },

    # ============================================================
    # AUTH FLOW
    # ============================================================
    "login": {
        "description": "User wants to login, signup, or authenticate",
        "aliases": ["signup", "authenticate"],
        "examples": [
            "login",
            "sign in",
            "I want to login",
            "login karna hai",
            "sign up",
            "create account",
            "register",
            "new account banana hai",
            "log in please",
            "mera account hai",
            "I have an account",
            "login karo",
            "sign in karo",
            "my phone number is 9876543210",
            "authenticate",
            "verify my account",
            "OTP bhejo",
            "send OTP",
            "enter OTP",
            "mera OTP hai 1234",
            "resend OTP",
            "OTP nahi aaya",
            "OTP expired",
            "login with phone number",
            "mobile number se login",
            "signup karna hai",
            "account create karo",
            "registration",
            "new user hun",
            "pehli baar use kar raha hun",
            "account nahi hai",
            "login kr do",
            "sign in kr do",
            "account banana h",
            "OTP bhejo mujhe",
            "login करा",
            "account बनवा",
            "OTP पाठवा",
            "login kara",
            "account banva",
            "OTP pathva",
            "sign up kara",
            "register kara",
            "navin account pahije",
            "OTP aale nahi",
            "verify kara",
        ],
    },

    # ============================================================
    # HELP FLOW
    # ============================================================
    "help": {
        "description": "User needs help or assistance with the bot",
        "aliases": ["assistance"],
        "examples": [
            "help",
            "help me",
            "I need help",
            "madad chahiye",
            "kya kar sakte ho?",
            "what can you do?",
            "how does this work?",
            "guide me",
            "help please",
            "show me how",
            "I'm confused",
            "I don't understand",
            "samajh nahi aa raha",
            "kaise use karu?",
            "kya kya kar sakte ho?",
            "features batao",
            "capabilities",
            "what services do you offer?",
            "how to order?",
            "ordering kaise karu?",
            "instructions do",
            "tutorial chahiye",
            "getting started",
            "how to use this",
            "kaise karu ye sab",
            "pehli baar hu, guide karo",
            "new hu, madad karo",
            "help karo",
            "kuch samajh nhi aa rha",
            "kaise order place karu",
            "kaise track karu",
            "payment kaise karu",
            "address kaise add karu",
            "how to cancel",
            "cancellation kaise karu",
            "refund kaise milega",
            "complaint kaise karu",
            "support chahiye",
            "FAQ",
            "frequently asked questions",
            "hlp",
            "help plz",
            "madad krdo",
            "kya kr skte ho",
            "guide kro",
            "मदत करा",
            "help करा",
            "कसं वापरायचं?",
            "madat kara",
            "help kara",
            "kasa vapraycha",
            "order kasa karaycha",
            "instructions dya",
            "guide kara mala",
        ],
    },

    # ============================================================
    # SUPPORT / COMPLAINT FLOW
    # ============================================================
    "complaint": {
        "description": "User has a complaint about order, delivery, quality",
        "aliases": ["contact_support", "support_request", "voice_feedback", "voice_repeat", "price_match"],
        "examples": [
            "I have a complaint",
            "complaint hai",
            "mera order galat aaya",
            "wrong order delivered",
            "food is cold",
            "quality bahut kharab hai",
            "worst food ever",
            "very bad experience",
            "I'm not happy with the order",
            "order mein item missing hai",
            "item galat hai",
            "delivery boy rude tha",
            "delivery bahut late hui",
            "2 hours late delivery",
            "food spilled",
            "packaging was bad",
            "stale food aaya",
            "quantity kam hai",
            "portion size very small",
            "not as described",
            "photo se alag hai",
            "unhygienic food",
            "hair in food",
            "insect in food",
            "food poisoning",
            "allergic reaction",
            "overcharged",
            "extra charge liya",
            "wrong amount charged",
            "double payment ho gaya",
            "refund nahi mila",
            "I want to speak to a human",
            "manager se baat karo",
            "contact support",
            "customer care",
            "support se baat karna hai",
            "agent se connect karo",
            "human agent chahiye",
            "real person se baat karo",
            "escalate my issue",
            "complaint register karo",
            "grievance hai",
            "price different from shown",
            "price mismatch",
            "price increase after ordering",
            "complaint h meri",
            "galat order aaya",
            "bahut bura experience",
            "support chahiye mujhe",
            "kisi se baat krao",
            "तक्रार आहे",
            "चुकीचा order आला",
            "quality खराब आहे",
            "complaint करायचं आहे",
            "takraar ahe",
            "chukicha order aala",
            "quality kharab ahe",
            "complaint karaycha ahe",
            "support shi baat karaychi ahe",
            "manager shi bola",
        ],
    },

    "payment_issue": {
        "description": "User has payment or wallet related issues",
        "aliases": ["check_wallet"],
        "examples": [
            "payment failed",
            "payment nahi hua",
            "transaction failed",
            "money deducted but order not placed",
            "paise kat gaye par order nahi hua",
            "double payment",
            "refund chahiye",
            "refund kab milega?",
            "where is my refund?",
            "payment issue",
            "payment problem",
            "UPI payment failed",
            "card payment not working",
            "net banking issue",
            "wallet se payment nahi ho raha",
            "payment decline ho gaya",
            "insufficient balance show ho raha",
            "payment pending hai",
            "check my wallet",
            "wallet balance kitna hai?",
            "wallet mein kitne paise hain?",
            "add money to wallet",
            "wallet recharge karo",
            "wallet balance check karo",
            "my wallet",
            "paytm wallet",
            "wallet se pay karo",
            "wallet balance use karo",
            "wallet mein paise daal do",
            "razorpay error",
            "payment gateway error",
            "timeout on payment",
            "payment pending status",
            "transaction ID check karo",
            "already paid",
            "already payment ho gaya",
            "payment receipt",
            "bill receipt chahiye",
            "invoice do",
            "paymnt fail",
            "paise cut gye",
            "refnd kab milega",
            "wallet blnce check kro",
            "payment nhi hua",
            "payment fail झालं",
            "पैसे कापले पण order नाही",
            "wallet balance किती?",
            "refund कधी मिळेल?",
            "payment fail jhala",
            "paise kaple pan order nahi",
            "wallet balance kiti",
            "refund kadhi milel",
            "payment problem ahe",
        ],
    },

    "refund_request": {
        "description": "User specifically requesting a refund",
        "aliases": [],
        "examples": [
            "I want a refund",
            "refund please",
            "refund chahiye",
            "give me my money back",
            "paise wapas karo",
            "refund karo",
            "money back",
            "return my money",
            "mujhe refund chahiye",
            "refund process karo",
            "refund kab milega",
            "refund request",
            "initiate refund",
            "full refund chahiye",
            "partial refund de do",
            "refund to wallet",
            "refund to bank",
            "refund to source",
            "original payment method pe refund",
            "refund abhi chahiye",
            "immediate refund",
            "instant refund",
            "jaldi refund karo",
            "why no refund yet?",
            "refund pending hai",
            "refund status check karo",
            "refund track karo",
            "where is my refund?",
            "refund approved?",
            "refund process ho gaya?",
            "refund kr do",
            "paise wapas kr do",
            "refnd chahiye",
            "money wapas kro",
            "refund करा",
            "पैसे परत करा",
            "refund कधी मिळेल?",
            "refund kara",
            "paise parat kara",
            "refund kadhi milel",
            "refund process kara",
            "instant refund pahije",
        ],
    },

    # ============================================================
    # GREETING / CHITCHAT / CONVERSATIONAL
    # ============================================================
    "greeting": {
        "description": "User greeting the bot",
        "aliases": ["hello"],
        "examples": [
            "hi",
            "hello",
            "hey",
            "namaste",
            "good morning",
            "good afternoon",
            "good evening",
            "good night",
            "hi there",
            "hello there",
            "hey there",
            "howdy",
            "what's up",
            "sup",
            "yo",
            "hiya",
            "greetings",
            "hi bot",
            "hello bot",
            "namaskar",
            "namaskaar",
            "pranam",
            "jai shree ram",
            "jai hind",
            "kya haal hai",
            "kaise ho",
            "how are you",
            "how's it going",
            "aur bhai",
            "kya chal raha hai",
            "hello ji",
            "hi ji",
            "arre bhai",
            "hellooo",
            "hiii",
            "heyy",
            "hiiii",
            "helllo",
            "helo",
            "hii",
            "hlw",
            "नमस्ते",
            "हाय",
            "हेलो",
            "कैसे हो",
            "नमस्कार",
            "namaskar",
            "kasa ahat",
            "kay challay",
            "hey mangwale",
            "hello mangwale",
            "hi mangwale",
            "good mrng",
            "gd morning",
            "gd evng",
            "gm",
            "ge",
            "gn",
            "subah ki namaste",
            "shubh prabhat",
            "शुभ प्रभात",
            "सुप्रभात",
        ],
    },

    "chitchat": {
        "description": "Casual conversation, small talk",
        "aliases": ["casual"],
        "examples": [
            "thank you",
            "thanks",
            "shukriya",
            "dhanyavaad",
            "thank you so much",
            "thanks a lot",
            "bahut shukriya",
            "you're the best",
            "great job",
            "awesome",
            "nice",
            "cool",
            "okay",
            "ok",
            "fine",
            "hmm",
            "lol",
            "haha",
            "that's funny",
            "who are you?",
            "what are you?",
            "are you a bot?",
            "are you AI?",
            "are you real?",
            "tumhara naam kya hai?",
            "what's your name?",
            "who made you?",
            "kisne banaya tumhe?",
            "tell me a joke",
            "joke sunao",
            "you're smart",
            "you're helpful",
            "tum acche ho",
            "bore ho raha hun",
            "I'm bored",
            "kuch interesting batao",
            "what do you think?",
            "tumhare baare mein batao",
            "how old are you?",
            "where are you from?",
            "tum kahan se ho?",
            "do you eat?",
            "kya tumhe bhook lagti hai?",
            "I love you",
            "you're cute",
            "mujhe tumse baat karni hai",
            "just chatting",
            "time pass",
            "nothing much",
            "kuch nahi bas aise hi",
            "random baat",
            "that's nice",
            "interesting",
            "accha",
            "theek hai",
            "haan bhai",
            "chal theek hai",
            "koi baat nahi",
            "no problem",
            "it's okay",
            "never mind",
            "sorry",
            "माफ करा",
            "धन्यवाद",
            "छान",
            "ठीक आहे",
            "dhanyavaad",
            "chhan",
            "theek ahe",
            "bhari",
            "mast",
            "ekdum barobar",
            "kay re",
            "aila",
            "bhari bhari",
        ],
    },

    "goodbye": {
        "description": "User saying goodbye",
        "aliases": [],
        "examples": [
            "bye",
            "goodbye",
            "see you",
            "see you later",
            "talk to you later",
            "bye bye",
            "tata",
            "alvida",
            "phir milenge",
            "chalo bye",
            "ok bye",
            "goodnight",
            "good night",
            "gotta go",
            "I'm leaving",
            "that's all",
            "bas itna hi",
            "nothing else",
            "aur kuch nahi",
            "I'm done",
            "ho gaya",
            "sab ho gaya",
            "close",
            "end chat",
            "stop",
            "quit",
            "exit",
            "thanks bye",
            "thank you bye",
            "shukriya bye",
            "dhanyavaad bye",
            "later",
            "cya",
            "bbye",
            "byee",
            "bb",
            "ok done bye",
            "chalo milte hain",
            "kal milte hain",
            "phir baat karte hain",
            "बाय",
            "पुन्हा भेटू",
            "चला निघतो",
            "bay",
            "punha bhetu",
            "chala nighto",
            "bye karto",
            "bas zala",
            "done ahe",
        ],
    },

    "confirm": {
        "description": "User confirming/agreeing with something",
        "aliases": ["affirm"],
        "examples": [
            "yes",
            "yeah",
            "yep",
            "yup",
            "sure",
            "okay",
            "ok",
            "haan",
            "ha",
            "ji haan",
            "bilkul",
            "zaroor",
            "of course",
            "definitely",
            "absolutely",
            "correct",
            "right",
            "that's right",
            "exactly",
            "sahi hai",
            "theek hai",
            "chalega",
            "done",
            "agreed",
            "confirm",
            "I confirm",
            "haan karo",
            "yes please",
            "go ahead",
            "proceed",
            "aage badho",
            "kar do",
            "haan bhai",
            "haan ji",
            "mujhe ye chahiye",
            "ye wala",
            "this one",
            "I agree",
            "accept",
            "perfect",
            "fine",
            "sounds good",
            "looks good",
            "great",
            "yes do it",
            "confirmed",
            "haan chalega",
            "ho",
            "hoye",
            "हो",
            "हां",
            "बरोबर",
            "चालेल",
            "ho",
            "hoy",
            "barobar",
            "chalel",
            "nakki",
            "yes kara",
            "haan kara",
        ],
    },

    "deny": {
        "description": "User denying/disagreeing/saying no",
        "aliases": [],
        "examples": [
            "no",
            "nope",
            "nah",
            "no thanks",
            "nahi",
            "nahi chahiye",
            "I don't want",
            "not this",
            "wrong",
            "that's wrong",
            "galat hai",
            "ye nahi",
            "kuch aur",
            "something else",
            "not this one",
            "different chahiye",
            "nahi nahi",
            "bilkul nahi",
            "never",
            "I refuse",
            "decline",
            "reject",
            "no way",
            "not at all",
            "not interested",
            "nahi chahiye mujhe",
            "change karo",
            "ye mat karo",
            "don't do this",
            "cancel karo",
            "I said no",
            "mujhe nahi chahiye",
            "hatao ye",
            "not now",
            "abhi nahi",
            "later",
            "baad mein",
            "ruko",
            "wait",
            "hold on",
            "nhi chahiye",
            "nhi",
            "galat h",
            "mt kro",
            "ruko abhi",
            "नाही",
            "नको",
            "चुकीचं आहे",
            "nahi",
            "nako",
            "chukicha ahe",
            "dusra dya",
            "he nako",
            "nahi pahije",
        ],
    },

    "feedback": {
        "description": "User giving feedback about their experience",
        "aliases": [],
        "examples": [
            "I want to give feedback",
            "feedback dena hai",
            "rate my experience",
            "review dena hai",
            "5 stars",
            "4 stars",
            "3 stars",
            "excellent service",
            "good service",
            "bad service",
            "average experience",
            "food was great",
            "food was okay",
            "food was bad",
            "delivery was fast",
            "delivery was slow",
            "packaging was good",
            "packaging was poor",
            "overall good experience",
            "could be better",
            "need improvement",
            "improvement chahiye",
            "loved it",
            "hated it",
            "not bad",
            "pretty good",
            "rating dena hai",
            "feedback submit karna hai",
            "experience share karna hai",
            "review likhna hai",
            "mera feedback hai ki...",
            "I want to rate",
            "star rating do",
            "bohot acha tha",
            "bahut bura tha",
            "decent tha",
            "mast tha",
            "bekar tha",
            "feedback share karna hai",
            "rate karo",
            "review de raha hun",
            "feedback kr rha hu",
            "review dena h",
            "rating deni h",
            "star dena h",
            "feedback द्यायचं आहे",
            "review द्या",
            "rating द्या",
            "feedback dyaycha ahe",
            "review dya",
            "rating dya",
            "mast hota",
            "chhan hota",
            "barobar nahi hota",
        ],
    },

    "human_takeover": {
        "description": "User explicitly wants to talk to a human agent",
        "aliases": [],
        "examples": [
            "talk to human",
            "I want a human",
            "connect me to agent",
            "real person please",
            "human agent chahiye",
            "insaan se baat karo",
            "bot se nahi, human se baat karo",
            "I want to speak to someone",
            "customer care se connect karo",
            "call center",
            "phone pe baat karo",
            "agent connect karo",
            "live chat agent",
            "executive se baat karna hai",
            "representative chahiye",
            "human se baat kr do",
            "insaan se baat krni h",
            "bot nhi human chahiye",
            "agent connect kro",
            "real person baat kro",
            "human से बोलायचं आहे",
            "agent connect करा",
            "माणसाशी बोला",
            "human shi bolaycha ahe",
            "agent connect kara",
            "manasashi bola",
            "customer care la lava",
            "support agent pahije",
            "live agent please",
            "supervisor se baat karo",
            "senior agent chahiye",
            "manager connect karo",
            "escalate to human",
            "transfer to agent",
            "I need real help",
            "bot se kuch nahi ho raha",
            "can I call someone?",
            "phone number do customer care ka",
            "helpline number",
            "kisi se baat karni hai urgently",
            "ye bot kaam nahi kar raha",
            "bot samajh nahi raha",
            "this bot is useless",
            "connect me to support team",
            "I want to escalate",
            "escalate this issue",
            "your bot is not helping",
            "mujhe kisi insaan se baat karni hai",
            "agent please",
            "human please",
            "person se baat karo please",
            "aadmi se baat karo",
            "koi aadmi bhejo",
            "real customer support",
            "main customer support se baat karna chahta hun",
            "operator",
            "connect to operator",
            "get me a person",
            "stop bot, give me human",
        ],
    },

    "use_saved": {
        "description": "User wants to use saved info (details, address, payment method)",
        "aliases": ["use_my_details"],
        "examples": [
            "use my saved address",
            "saved address use karo",
            "pehle wala address",
            "home address pe bhejo",
            "office address use karo",
            "default address",
            "same address as last time",
            "use saved details",
            "meri saved info use karo",
            "pehle wali details",
            "same details",
            "use my profile",
            "my saved card",
            "saved payment method use karo",
            "UPI saved hai, wo use karo",
            "my name is Raj",
            "Rahul 9876543210",
            "raj 9923456789",
            "shantanu 9370407508",
            "akash 9923383838",
            "my number is 9876543210",
            "Amit Kumar 9871234567",
            "Priya Sharma 9998887776",
            "call me on 9876543210",
            "contact: 9876543210",
            "use last order address",
            "last time ka address",
            "jo address save hai wo",
            "previous address",
            "saved wala use karo",
            "mere details use kro",
            "saved address use kro",
            "same details as before",
            "meri info use kro",
            "saved address वापरा",
            "माझी details वापरा",
            "saved address vapra",
            "mazhi details vapra",
            "aadhi cha address",
            "same address vapra",
            "saved info vapra",
            "profile madhlya details",
        ],
    },
}

# ============================================================
# GENERATE FINAL TRAINING FILE
# ============================================================

def generate_training_data():
    all_samples = []
    stats = {}

    for intent, data in TRAINING_DATA.items():
        examples = data["examples"]
        stats[intent] = len(examples)
        for text in examples:
            all_samples.append({
                "text": text.strip(),
                "intent": intent,
            })

    # Shuffle
    random.shuffle(all_samples)

    # Write
    output_path = os.path.join(os.path.dirname(__file__), "nlu_final_v5_production.jsonl")
    with open(output_path, "w") as f:
        for sample in all_samples:
            f.write(json.dumps(sample, ensure_ascii=False) + "\n")

    print(f"Generated {len(all_samples)} samples across {len(stats)} intents")
    print(f"\nPer-intent distribution:")
    for intent, count in sorted(stats.items(), key=lambda x: -x[1]):
        print(f"  {count:4d}  {intent}")

    # Also write intent mapping (canonical → aliases)
    mapping_path = os.path.join(os.path.dirname(__file__), "intent_mapping_v5.json")
    mapping = {}
    for intent, data in TRAINING_DATA.items():
        mapping[intent] = {
            "description": data["description"],
            "aliases": data["aliases"],
            "sample_count": stats[intent],
        }
    with open(mapping_path, "w") as f:
        json.dump(mapping, f, indent=2, ensure_ascii=False)

    print(f"\nFiles written:")
    print(f"  {output_path}")
    print(f"  {mapping_path}")

if __name__ == "__main__":
    generate_training_data()
