// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/agent-testing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agent-testing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/agent-testing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/flows/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/flows/editor">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/flows/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/flows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/flows">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/flows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/llm-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/llm-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/llm-chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-chat">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/llm-chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/llm-models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-models">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/llm-models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/llm-providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-providers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/llm-providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/models">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/modules/[module]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/[module]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/modules/[module]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/nlu-testing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/nlu-testing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/nlu-testing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/nlu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/nlu">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/nlu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/search-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/search-analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/search-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/search-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/search-config">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/search-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/training/datasets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/training/datasets/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/training/datasets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/training/datasets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/training/datasets">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/training/datasets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/training/jobs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/training/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/training/jobs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/training">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trending">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vision/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vision/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vision/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vision/camera-enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vision/camera-enrollment">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vision/camera-enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vision/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vision/employees">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vision/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vision/enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vision/enrollment">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vision/enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vision/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vision/monitoring">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vision/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vision/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vision">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vision/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/vllm-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vllm-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/vllm-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/webhooks">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/attendance/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/attendance/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/attendance/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/attendance/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/attendance/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/attendance/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/cameras/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/cameras">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/cameras/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/cameras/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/cameras/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/cameras/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/check-rider/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/check-rider">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/check-rider/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/employees/[id]/deactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/employees/[id]/deactivate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/employees/[id]/deactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/employees/[id]/reactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/employees/[id]/reactivate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/employees/[id]/reactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/employees/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/employees/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/employees/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/employees/enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/employees/enroll">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/employees/enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/employees">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/employees/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/employees/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/employees/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/enroll-employee/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/enroll-employee">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/enroll-employee/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/live-stream/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/live-stream/active">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/live-stream/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vision/live-stream/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vision/live-stream/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vision/live-stream/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
