// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/agent-testing" | "/admin/agents" | "/admin/api-keys" | "/admin/audit-logs" | "/admin/dashboard" | "/admin/flows" | "/admin/models" | "/admin/modules/[module]" | "/admin/nlu" | "/admin/nlu-testing" | "/admin/search-analytics" | "/admin/search-config" | "/admin/settings" | "/admin/training" | "/admin/training/datasets" | "/admin/training/datasets/[id]" | "/admin/training/jobs/[id]" | "/admin/trending" | "/admin/vision" | "/admin/webhooks" | "/chat" | "/login" | "/orders" | "/profile" | "/search"
type AppRouteHandlerRoutes = "/api/vision/check-rider"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/agent-testing": {}
  "/admin/agents": {}
  "/admin/api-keys": {}
  "/admin/audit-logs": {}
  "/admin/dashboard": {}
  "/admin/flows": {}
  "/admin/models": {}
  "/admin/modules/[module]": { "module": string; }
  "/admin/nlu": {}
  "/admin/nlu-testing": {}
  "/admin/search-analytics": {}
  "/admin/search-config": {}
  "/admin/settings": {}
  "/admin/training": {}
  "/admin/training/datasets": {}
  "/admin/training/datasets/[id]": { "id": string; }
  "/admin/training/jobs/[id]": { "id": string; }
  "/admin/trending": {}
  "/admin/vision": {}
  "/admin/webhooks": {}
  "/api/vision/check-rider": {}
  "/chat": {}
  "/login": {}
  "/orders": {}
  "/profile": {}
  "/search": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
